PROGRAM = test_bench_resultpool

SRCS = $(PROGRAM).lpr \
       $(SRC_DIR)/nextpas.core.bench.base.pas \
       $(SRC_DIR)/nextpas.core.bench.run.pas \
       $(SRC_DIR)/nextpas.core.bench.resultpool.pas \
       $(SRC_DIR)/nextpas.core.atomic.pas \
       $(SRC_DIR)/nextpas.core.atomic.types.pas \
       $(SRC_DIR)/nextpas.core.atomic.core.pas \
       $(SRC_DIR)/nextpas.core.atomic.compat.pas \
       $(SRC_DIR)/nextpas.core.errors.pas \
       $(SRC_DIR)/nextpas.core.platform.thread.pas \
       $(SRC_DIR)/nextpas.core.platform.base.pas \
       $(SRC_DIR)/nextpas.core.sync.mutex.pas \
       $(SRC_DIR)/nextpas.core.thread.init.pas

include ../bench_test_common.mk
