#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
LOG_PATH="${1:-${ROOT}/logs/windows_b07_gate.simulated.log}"
LOG_BASE="$(basename "${LOG_PATH}")"
SUMMARY_JSON_SENTINEL="${LOG_PATH%.log}.summary-json.missing"

print_usage() {
  echo "Usage: $0 [simulated-log-path]"
  echo "Default log: ${ROOT}/logs/windows_b07_gate.simulated.log"
  echo "Note: writing windows_b07_gate.log is blocked by design."
}

if [[ "${LOG_PATH}" == "-h" || "${LOG_PATH}" == "--help" ]]; then
  print_usage
  exit 0
fi

if [[ "${LOG_BASE}" == "windows_b07_gate.log" ]]; then
  echo "[SIMULATE] Refuse target: ${LOG_PATH}"
  echo "[SIMULATE] windows_b07_gate.log is reserved for real Windows evidence only."
  exit 2
fi

if [[ "${LOG_BASE}" != *.simulated.log ]]; then
  echo "[SIMULATE] Refuse target: ${LOG_PATH}"
  echo "[SIMULATE] simulated output file name must end with .simulated.log"
  exit 2
fi

mkdir -p "$(dirname "${LOG_PATH}")"

cat > "${LOG_PATH}" <<EOM
[B07] Windows evidence capture
[SIMULATE] Generated by simulate_windows_b07_evidence.sh (do not treat as real Windows evidence)
[B07] Source: collect_windows_b07_evidence.bat
[B07] HostOS: Windows_NT
[B07] CmdVer: Microsoft Windows [Version 10.0.22631.0]
[B07] Started: $(date '+%Y/%m/%d %H:%M:%S.00')
[B07] Working dir: C:\simd\tests\nextpas.core.simd\
[B07] Command: buildOrTest.bat gate
[B07] GateSummaryJson: ${SUMMARY_JSON_SENTINEL}

[GATE] 1/6 Build + check SIMD module
[BACKEND-OPS] Building standalone program: C:\simd\tests\nextpas.core.simd\test_backend_ops.pas
[BACKEND-OPS] Running standalone program: C:\simd\tests\nextpas.core.simd\backend.ops\bin\test_backend_ops.exe
[SIMD-BOUNDARY] Building standalone program: C:\simd\tests\nextpas.core.simd\test_simd_boundary.pas
[SIMD-BOUNDARY] Running standalone program: C:\simd\tests\nextpas.core.simd\simd.boundary\bin\test_simd_boundary.exe
[PUBLIC-SMOKE] Building standalone smoke: C:\simd\tests\nextpas.core.simd\nextpas.core.simd.public_smoke.pas
[PUBLIC-SMOKE] Running standalone smoke: C:\simd\tests\nextpas.core.simd\public.smoke\bin\nextpas.core.simd.public_smoke.exe
[PASS] Default backend is AVX2
[DISPATCH-PREINIT] Building standalone smoke: C:\simd\tests\nextpas.core.simd\nextpas.core.simd.dispatch_preinit_smoke.pas
[DISPATCH-PREINIT] Running standalone smoke: C:\simd\tests\nextpas.core.simd\dispatch.preinit.smoke\bin\nextpas.core.simd.dispatch_preinit_smoke.exe
[DISPATCH-PREINIT] OK
[GATE] Optional public ABI smoke
[GATE] 2/6 SIMD list suites
[GATE] 3/6 SIMD AVX2 stable vector suites
[GATE] 4/6 CPUInfo portable suites
[GATE] 5/6 CPUInfo x86 suites
[GATE] 6/6 Filtered run_all check chain
[GATE] OK

[B07] GATE_EXIT_CODE=0

[B07] run_all summary snapshot
Total:  5
Passed: 5
Failed: 0
[B07] Total: 5
[B07] Passed: 5
[B07] Failed: 0
EOM

echo "[SIMULATE] OK: ${LOG_PATH}"
