#!/usr/bin/env python3
"""Generate golden verify vectors for the TLS 1.3 server CertificateVerify
RSA verify contract test (test_tls13_servercertverify_verify).

Reproducible: run from core/tests/nextpas.core.tls/test_tls13_servercertverify_verify
with openssl available.  The message is the exact CertificateVerify input
layout used by the unit (context string + transcript hash); signatures are
made with the checked-in signer key, so no key material is embedded.
"""
import hashlib
import os
import subprocess
import sys

KEY = os.path.join('..', 'certificate', 'test_certs', 'signer_key.pem')
PREFIX = b'TLS 1.3, server CertificateVerify'

def sh(args):
    return subprocess.run(args, check=True, stdout=subprocess.PIPE).stdout

def gen(transcript: bytes, hashname: str, pss: bool, saltlen: int) -> bytes:
    msg = PREFIX + transcript
    args = ['openssl', 'dgst', '-' + hashname, '-sign', KEY]
    if pss:
        args += ['-sigopt', 'rsa_padding_mode:pss', '-sigopt', 'rsa_pss_saltlen:%d' % saltlen]
    open('_msg.bin', 'wb').write(msg)
    sig = sh(args + ['_msg.bin'])
    os.remove('_msg.bin')
    return sig

def main():
    tr256 = bytes(range(0x21, 0x21 + 32))
    tr384 = bytes(range(0x61, 0x61 + 48))
    msg256 = PREFIX + tr256
    msg384 = PREFIX + tr384
    sigs = {
        'SIG_PKCS1_SHA256_HEX': gen(tr256, 'sha256', False, 0),
        'SIG_PKCS1_SHA384_HEX': gen(tr384, 'sha384', False, 0),
        'SIG_PSS_SHA256_HEX': gen(tr256, 'sha256', True, 32),
        'SIG_PSS_SHA384_HEX': gen(tr384, 'sha384', True, 48),
    }

    # modulus/exponent from the signer key's public half (SPKI), leading zero stripped
    pubder = sh(['openssl', 'pkey', '-in', KEY, '-pubout', '-outform', 'DER'])
    assert pubder[0] == 0x30
    i = 1
    def rd_len(d, i):
        l = d[i]; i += 1
        if l & 0x80:
            n = l & 0x7f; l = int.from_bytes(d[i:i+n], 'big'); i += n
        return l, i
    ln, i = rd_len(pubder, i)          # SPKI seq
    assert pubder[i] == 0x30
    ln, i = rd_len(pubder, i + 1)      # alg seq
    i += ln
    assert pubder[i] == 0x03
    ln, i = rd_len(pubder, i + 1)      # bit string
    i += 1
    assert pubder[i] == 0x30
    ln, i = rd_len(pubder, i + 1)      # pubkey seq
    assert pubder[i] == 0x02
    ln, i = rd_len(pubder, i + 1)
    modulus = pubder[i:i + ln]; i += ln
    assert pubder[i] == 0x02
    ln, i = rd_len(pubder, i + 1)
    exponent = pubder[i:i + ln]
    if modulus[0] == 0:
        modulus = modulus[1:]
    assert len(modulus) == 256

    def hexl(b):
        return b.hex()

    out = '''program test_tls13_servercertverify_verify;

{$mode ObjFPC}{$H+}

uses
  nextpas.core.system.sysutils,
  nextpas.core.tls.tls13.servercertverify;

const
  { Golden vectors generated by gen_vectors.py against
    tests/certificate/test_certs/signer_key.pem (RFC 8446 §4.4.3 input
    layout: "TLS 1.3, server CertificateVerify" + transcript hash). }
  MESSAGE_SHA256_HEX = '%s';
  MESSAGE_SHA384_HEX = '%s';
  RSA2048_MODULUS_HEX = '%s';
  RSA2048_EXPONENT_HEX = '%s';
  SIG_PKCS1_SHA256_HEX = '%s';
  SIG_PKCS1_SHA384_HEX = '%s';
  SIG_PSS_SHA256_HEX = '%s';
  SIG_PSS_SHA384_HEX = '%s';

function HexDigitToValue(const AChar: Char): Integer;
begin
  case AChar of
    '0'..'9': Result := Ord(AChar) - Ord('0');
    'a'..'f': Result := 10 + Ord(AChar) - Ord('a');
    'A'..'F': Result := 10 + Ord(AChar) - Ord('A');
  else
    Result := -1;
  end;
end;

function HexToBytes(const AHex: string): TBytes;
var
  I, LHigh, LLow: Integer;
begin
  if (Length(AHex) mod 2) <> 0 then
    Exit(nil);
  SetLength(Result, Length(AHex) div 2);
  for I := 0 to High(Result) do
  begin
    LHigh := HexDigitToValue(AHex[2 * I + 1]);
    LLow := HexDigitToValue(AHex[2 * I + 2]);
    if (LHigh < 0) or (LLow < 0) then
      Exit(nil);
    Result[I] := Byte((LHigh shl 4) or LLow);
  end;
end;

procedure Check(ACondition: Boolean; const AMessage: string);
begin
  if not ACondition then
  begin
    WriteLn('FAIL: ', AMessage);
    Halt(1);
  end;
end;

procedure CheckVerifyPKCS1SHA256;
var
  LMsg, LSig, LMsg2, LMod, LExp: TBytes;
  LErr: string;
begin
  LMsg := HexToBytes(MESSAGE_SHA256_HEX);
  LMsg2 := HexToBytes(MESSAGE_SHA384_HEX);
  LSig := HexToBytes(SIG_PKCS1_SHA256_HEX);
  LMod := HexToBytes(RSA2048_MODULUS_HEX);
  LExp := HexToBytes(RSA2048_EXPONENT_HEX);
  Check(Length(LMod) = 256, 'modulus constant must decode to 256 bytes');

  LErr := '';
  Check(TryVerifyRSAPKCS1v15SignatureSHA256(LMsg, LSig, LMod, LExp, LErr),
    'PKCS1-SHA256 valid signature must verify: ' + LErr);

  LSig[0] := LSig[0] xor $01;
  LErr := '';
  Check(not TryVerifyRSAPKCS1v15SignatureSHA256(LMsg, LSig, LMod, LExp, LErr),
    'PKCS1-SHA256 tampered signature must be rejected');

  LErr := '';
  Check(not TryVerifyRSAPKCS1v15SignatureSHA256(LMsg2,
    HexToBytes(SIG_PKCS1_SHA256_HEX), LMod, LExp, LErr),
    'PKCS1-SHA256 signature over a different message must be rejected');
end;

procedure CheckVerifyPKCS1SHA384;
var
  LMsg, LSig, LMsg2, LMod, LExp: TBytes;
  LErr: string;
begin
  LMsg := HexToBytes(MESSAGE_SHA384_HEX);
  LMsg2 := HexToBytes(MESSAGE_SHA256_HEX);
  LSig := HexToBytes(SIG_PKCS1_SHA384_HEX);
  LMod := HexToBytes(RSA2048_MODULUS_HEX);
  LExp := HexToBytes(RSA2048_EXPONENT_HEX);

  LErr := '';
  Check(TryVerifyRSAPKCS1v15SignatureSHA384(LMsg, LSig, LMod, LExp, LErr),
    'PKCS1-SHA384 valid signature must verify: ' + LErr);

  LSig[High(LSig)] := LSig[High(LSig)] xor $80;
  LErr := '';
  Check(not TryVerifyRSAPKCS1v15SignatureSHA384(LMsg, LSig, LMod, LExp, LErr),
    'PKCS1-SHA384 tampered signature must be rejected');

  LErr := '';
  Check(not TryVerifyRSAPKCS1v15SignatureSHA384(LMsg2,
    HexToBytes(SIG_PKCS1_SHA384_HEX), LMod, LExp, LErr),
    'PKCS1-SHA384 signature over a different message must be rejected');
end;

procedure CheckVerifyPSSSHA256;
var
  LMsg, LSig, LMsg2, LMod, LExp: TBytes;
  LErr: string;
begin
  LMsg := HexToBytes(MESSAGE_SHA256_HEX);
  LMsg2 := HexToBytes(MESSAGE_SHA384_HEX);
  LSig := HexToBytes(SIG_PSS_SHA256_HEX);
  LMod := HexToBytes(RSA2048_MODULUS_HEX);
  LExp := HexToBytes(RSA2048_EXPONENT_HEX);

  LErr := '';
  Check(TryVerifyRSAPSSSignatureSHA256(LMsg, LSig, LMod, LExp, LErr),
    'PSS-SHA256 valid signature must verify: ' + LErr);

  LSig[0] := LSig[0] xor $01;
  LErr := '';
  Check(not TryVerifyRSAPSSSignatureSHA256(LMsg, LSig, LMod, LExp, LErr),
    'PSS-SHA256 tampered signature must be rejected');

  LErr := '';
  Check(not TryVerifyRSAPSSSignatureSHA256(LMsg2,
    HexToBytes(SIG_PSS_SHA256_HEX), LMod, LExp, LErr),
    'PSS-SHA256 signature over a different message must be rejected');
end;

procedure CheckVerifyPSSSHA384;
var
  LMsg, LSig, LMsg2, LMod, LExp: TBytes;
  LErr: string;
begin
  LMsg := HexToBytes(MESSAGE_SHA384_HEX);
  LMsg2 := HexToBytes(MESSAGE_SHA256_HEX);
  LSig := HexToBytes(SIG_PSS_SHA384_HEX);
  LMod := HexToBytes(RSA2048_MODULUS_HEX);
  LExp := HexToBytes(RSA2048_EXPONENT_HEX);

  LErr := '';
  Check(TryVerifyRSAPSSSignatureSHA384(LMsg, LSig, LMod, LExp, LErr),
    'PSS-SHA384 valid signature must verify: ' + LErr);

  LSig[High(LSig)] := LSig[High(LSig)] xor $80;
  LErr := '';
  Check(not TryVerifyRSAPSSSignatureSHA384(LMsg, LSig, LMod, LExp, LErr),
    'PSS-SHA384 tampered signature must be rejected');

  LErr := '';
  Check(not TryVerifyRSAPSSSignatureSHA384(LMsg2,
    HexToBytes(SIG_PSS_SHA384_HEX), LMod, LExp, LErr),
    'PSS-SHA384 signature over a different message must be rejected');
end;

begin
  WriteLn('Testing TLS 1.3 server CertificateVerify RSA verify contract...');
  CheckVerifyPKCS1SHA256;
  CheckVerifyPKCS1SHA384;
  CheckVerifyPSSSHA256;
  CheckVerifyPSSSHA384;
  WriteLn('OK: all RSA verify contract checks passed');
end.
''' % (msg256.hex(), msg384.hex(), modulus.hex(), exponent.hex(),
       sigs['SIG_PKCS1_SHA256_HEX'].hex(), sigs['SIG_PKCS1_SHA384_HEX'].hex(),
       sigs['SIG_PSS_SHA256_HEX'].hex(), sigs['SIG_PSS_SHA384_HEX'].hex())

    with open('test_tls13_servercertverify_verify.lpr', 'w') as f:
        f.write(out)
    print('wrote test_tls13_servercertverify_verify.lpr')

if __name__ == '__main__':
    main()
