program test_tls13_servercertverify_verify;

{$mode ObjFPC}{$H+}

uses
  nextpas.core.system.sysutils,
  nextpas.core.tls.tls13.servercertverify;

const
  { Golden vectors generated by gen_vectors.py against
    tests/certificate/test_certs/signer_key.pem (RFC 8446 §4.4.3 input
    layout: "TLS 1.3, server CertificateVerify" + transcript hash). }
  MESSAGE_SHA256_HEX = '544c5320312e332c207365727665722043657274696669636174655665726966792122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40';
  MESSAGE_SHA384_HEX = '544c5320312e332c207365727665722043657274696669636174655665726966796162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f90';
  RSA2048_MODULUS_HEX = 'cafbc3e51b6285529189ff9549d3eee52428808525db08ca09ef00d21d0096e3856abe7f44e2f905a2c800a49c654b4e0840019c475b302d5923325fa10e34a13370d1ed20bc1364608b446de1975b1eab73cf602991181cfe1c2b1c7163a9ac2457d95a3c0b91fc1c6cc70e36d44760372bac2a04c83a2e483a0180fc0ec7fc6aa4e6f449a9fdb14e8e8d63d1b832cb0c8fad2b6410caecd742259891f98d94ae06f6f42812e9574dbe20ae87e0a481fc086b2fe6eadd38bca5d19d3abadde69630dbbfb9ae825222d0e86d53cfd73b777437bc15554b81c289b92391e2ea1a3ed303d21ca5f53104c628773b6668102da33a4e0fe873a771a5512002c1fc7f';
  RSA2048_EXPONENT_HEX = '010001';
  SIG_PKCS1_SHA256_HEX = '37c59c3a54fcc44cd01c6dcafcb96848f0f00f86cd8c5ad914073bbed302a2f238116f437c7dfbf334eb83a0e8a7411743aedbb878dadbe280b758a4b0621a437818c1e3ca9e45f784ef25c70d0ec72736aecf9814bea7f9d01ec2d5ef1c75055d9cb3770572d86fc3009bf058dd36c50a1966b511101a3a7105969750043ccb5b40ae4acaecb0c47d1dc19d82770d41338420693a91913f97f81acf167261fb0d7b71c4c87c4c06ffd71ded47fdf7687d25cb74e2a35622d6255df808885aba8015b198a44b1c25e02b5e3596d2e2c6c5a6e255f99c177189b9f36d15148ba847b7c49c24714d906af00a42fdc2d5ca6bc8bd47b7c533ff9ef73b7036c8dabd';
  SIG_PKCS1_SHA384_HEX = '236d395b2f22c2ed917194eccc5611ae5e3658004125e03dc34e248a90abb65d135bccceb66fb62571074f489e5adedc39e9d5d48c1a5e595ef062e16ad30ad9257994f27e5b02669aea333fc8ae3383350548ce4bb361a8b2a6e14e3c0c8d84cc77ff62ff14ce083bd58f5b52e2a42abfc2f046d8dfc68d6296bfdf6fbf70250d25dbd3916ebe9c7d56e363b9572ec8073e24be85f9da3fd9c76ca7cf27b76e12d8fadd6f82a44ff8dab061379e38b973c4daf7fd9723189368330e200a0f9d9200cc13198ce570b50c994f988a1401770ab4bf44793fc4ccc79c057fcb7ca8168e3151eda49ad9f326416950a65dfa308baecb1b290402ba6d5894314dc4c0';
  SIG_PSS_SHA256_HEX = '998b7d2dbcbf4f837da7b262528d6e6f4947ed2218c26ff6cb3793026afd119c2eaf1fc30b14eca30d3454883bb3c4a5e2fe36d468647dcbae60ebf27c6cfa3697647cc7ce52eb4bce50251ed2c0ab829363e639f8de1bc0c4a31a57a43b730b16fc7a64c543806fe1247eb91279d24309d738aedc776388986415c71c4f77be5284bde7d04da2719838ed4a32336d8f4c7f6ed8c17a746cf0adeedae564abdfe153f6abb8d57b2c875d3bcefe5e3af3bef87ccc89716445b81a081d71bc0bc69fbb097a6567d0e283a790260f9eebed000d85cf9d5718b0cda180183c0fa7aeb7b37d5b4b814d680bb2d41b625e9ae52b13fc3ca2fcc06f47231eb3e0f48d00';
  SIG_PSS_SHA384_HEX = '494ede3088a7e3013f1cb861c85f5198e980278ff5aade068cef90f5841b12f4dbfae94dc444b71cfac214df76c0ba4914b77d054af48d42f60b5d5aa0544568a92798322a8082bdcd5aafde99817677dd4994d7e6a547120287c0fea6f7247298ff982cadd0d9eed2c1ff7491c81807e93d8dd8417c1082e92239f2abd545bd963063706e5bdfc685b35c2c77cd508d66c87671663371a2f83b3050c23aa8bbf9e614ab09e10ff54d7bac5b17c6cac1a5ec0f1eb0b9b877304b736a1f7b82252d32dbd7bcdc589aa72154c96208d42629be22a6af1e251f51ae4791cc24e29967c5cdd28862a91fd83c7a63101fb8a51c0f67d1d58d68f0fff3a8ae27a15aa5';

function HexDigitToValue(const AChar: Char): Integer;
begin
  case AChar of
    '0'..'9': Result := Ord(AChar) - Ord('0');
    'a'..'f': Result := 10 + Ord(AChar) - Ord('a');
    'A'..'F': Result := 10 + Ord(AChar) - Ord('A');
  else
    Result := -1;
  end;
end;

function HexToBytes(const AHex: string): TBytes;
var
  I, LHigh, LLow: Integer;
begin
  if (Length(AHex) mod 2) <> 0 then
    Exit(nil);
  SetLength(Result, Length(AHex) div 2);
  for I := 0 to High(Result) do
  begin
    LHigh := HexDigitToValue(AHex[2 * I + 1]);
    LLow := HexDigitToValue(AHex[2 * I + 2]);
    if (LHigh < 0) or (LLow < 0) then
      Exit(nil);
    Result[I] := Byte((LHigh shl 4) or LLow);
  end;
end;

procedure Check(ACondition: Boolean; const AMessage: string);
begin
  if not ACondition then
  begin
    WriteLn('FAIL: ', AMessage);
    Halt(1);
  end;
end;

procedure CheckVerifyPKCS1SHA256;
var
  LMsg, LSig, LMsg2, LMod, LExp: TBytes;
  LErr: string;
begin
  LMsg := HexToBytes(MESSAGE_SHA256_HEX);
  LMsg2 := HexToBytes(MESSAGE_SHA384_HEX);
  LSig := HexToBytes(SIG_PKCS1_SHA256_HEX);
  LMod := HexToBytes(RSA2048_MODULUS_HEX);
  LExp := HexToBytes(RSA2048_EXPONENT_HEX);
  Check(Length(LMod) = 256, 'modulus constant must decode to 256 bytes');

  LErr := '';
  Check(TryVerifyRSAPKCS1v15SignatureSHA256(LMsg, LSig, LMod, LExp, LErr),
    'PKCS1-SHA256 valid signature must verify: ' + LErr);

  LSig[0] := LSig[0] xor $01;
  LErr := '';
  Check(not TryVerifyRSAPKCS1v15SignatureSHA256(LMsg, LSig, LMod, LExp, LErr),
    'PKCS1-SHA256 tampered signature must be rejected');

  LErr := '';
  Check(not TryVerifyRSAPKCS1v15SignatureSHA256(LMsg2,
    HexToBytes(SIG_PKCS1_SHA256_HEX), LMod, LExp, LErr),
    'PKCS1-SHA256 signature over a different message must be rejected');
end;

procedure CheckVerifyPKCS1SHA384;
var
  LMsg, LSig, LMsg2, LMod, LExp: TBytes;
  LErr: string;
begin
  LMsg := HexToBytes(MESSAGE_SHA384_HEX);
  LMsg2 := HexToBytes(MESSAGE_SHA256_HEX);
  LSig := HexToBytes(SIG_PKCS1_SHA384_HEX);
  LMod := HexToBytes(RSA2048_MODULUS_HEX);
  LExp := HexToBytes(RSA2048_EXPONENT_HEX);

  LErr := '';
  Check(TryVerifyRSAPKCS1v15SignatureSHA384(LMsg, LSig, LMod, LExp, LErr),
    'PKCS1-SHA384 valid signature must verify: ' + LErr);

  LSig[High(LSig)] := LSig[High(LSig)] xor $80;
  LErr := '';
  Check(not TryVerifyRSAPKCS1v15SignatureSHA384(LMsg, LSig, LMod, LExp, LErr),
    'PKCS1-SHA384 tampered signature must be rejected');

  LErr := '';
  Check(not TryVerifyRSAPKCS1v15SignatureSHA384(LMsg2,
    HexToBytes(SIG_PKCS1_SHA384_HEX), LMod, LExp, LErr),
    'PKCS1-SHA384 signature over a different message must be rejected');
end;

procedure CheckVerifyPSSSHA256;
var
  LMsg, LSig, LMsg2, LMod, LExp: TBytes;
  LErr: string;
begin
  LMsg := HexToBytes(MESSAGE_SHA256_HEX);
  LMsg2 := HexToBytes(MESSAGE_SHA384_HEX);
  LSig := HexToBytes(SIG_PSS_SHA256_HEX);
  LMod := HexToBytes(RSA2048_MODULUS_HEX);
  LExp := HexToBytes(RSA2048_EXPONENT_HEX);

  LErr := '';
  Check(TryVerifyRSAPSSSignatureSHA256(LMsg, LSig, LMod, LExp, LErr),
    'PSS-SHA256 valid signature must verify: ' + LErr);

  LSig[0] := LSig[0] xor $01;
  LErr := '';
  Check(not TryVerifyRSAPSSSignatureSHA256(LMsg, LSig, LMod, LExp, LErr),
    'PSS-SHA256 tampered signature must be rejected');

  LErr := '';
  Check(not TryVerifyRSAPSSSignatureSHA256(LMsg2,
    HexToBytes(SIG_PSS_SHA256_HEX), LMod, LExp, LErr),
    'PSS-SHA256 signature over a different message must be rejected');
end;

procedure CheckVerifyPSSSHA384;
var
  LMsg, LSig, LMsg2, LMod, LExp: TBytes;
  LErr: string;
begin
  LMsg := HexToBytes(MESSAGE_SHA384_HEX);
  LMsg2 := HexToBytes(MESSAGE_SHA256_HEX);
  LSig := HexToBytes(SIG_PSS_SHA384_HEX);
  LMod := HexToBytes(RSA2048_MODULUS_HEX);
  LExp := HexToBytes(RSA2048_EXPONENT_HEX);

  LErr := '';
  Check(TryVerifyRSAPSSSignatureSHA384(LMsg, LSig, LMod, LExp, LErr),
    'PSS-SHA384 valid signature must verify: ' + LErr);

  LSig[High(LSig)] := LSig[High(LSig)] xor $80;
  LErr := '';
  Check(not TryVerifyRSAPSSSignatureSHA384(LMsg, LSig, LMod, LExp, LErr),
    'PSS-SHA384 tampered signature must be rejected');

  LErr := '';
  Check(not TryVerifyRSAPSSSignatureSHA384(LMsg2,
    HexToBytes(SIG_PSS_SHA384_HEX), LMod, LExp, LErr),
    'PSS-SHA384 signature over a different message must be rejected');
end;

begin
  WriteLn('Testing TLS 1.3 server CertificateVerify RSA verify contract...');
  CheckVerifyPKCS1SHA256;
  CheckVerifyPKCS1SHA384;
  CheckVerifyPSSSHA256;
  CheckVerifyPSSSHA384;
  WriteLn('OK: all RSA verify contract checks passed');
end.
