PROGRAM := test_zip_perf
# perf allocs counted without heaptrc bookkeeping interference; baseline from BASELINE.json
HEAPTRC_GATE = 0
BASE_FPC_FLAGS = -MObjFPC -Sh -Sg -O2 -gl
include ../../common.mk
