program test_conformance_normalize;
{**
 * Unicode 16.0 NormalizationTest official conformance harness.
 *
 * Fixture: ../data/normalization_test.txt
 * Generated by: core/scripts/gen_unicode_fixtures.py
 *
 * For each row c1;c2;c3;c4;c5 (UAX #15 §NormalizationTest):
 *   c2 = NFC(c1) = NFC(c2) = NFC(c3)
 *   c4 = NFC(c4) = NFC(c5)
 *   c3 = NFD(c1) = NFD(c2) = NFD(c3)
 *   c5 = NFD(c4) = NFD(c5)
 *   c4 = NFKC(c1) = NFKC(c2) = NFKC(c3) = NFKC(c4) = NFKC(c5)
 *   c5 = NFKD(c1) = NFKD(c2) = NFKD(c3) = NFKD(c4) = NFKD(c5)
 *}

{$I nextpas.core.settings.inc}

uses
  nextpas.core.fs,
  nextpas.core.text,
  nextpas.core.test,
  nextpas.core.text.utf8,
  nextpas.core.text.unicode.base,
  nextpas.core.text.unicode;

var
  T: TTestSuite;

{$I ../test_helpers.inc}

function ResolveFixture(const AName: string): string;
begin
  if FileExists('../data/' + AName) then
    Exit('../data/' + AName);
  if FileExists('core/tests/nextpas.core.text.unicode/data/' + AName) then
    Exit('core/tests/nextpas.core.text.unicode/data/' + AName);
  if FileExists('../../nextpas.core.text.unicode/data/' + AName) then
    Exit('../../nextpas.core.text.unicode/data/' + AName);
  Result := '../data/' + AName;
end;

function ParseHexDigit(const ACh: Char): Integer;
begin
  case ACh of
    '0'..'9': Result := Ord(ACh) - Ord('0');
    'a'..'f': Result := Ord(ACh) - Ord('a') + 10;
    'A'..'F': Result := Ord(ACh) - Ord('A') + 10;
  else
    Result := -1;
  end;
end;

function ParseHexCodepoint(const AHex: string): TUnicodeCodepoint;
var
  I: Integer;
  LDigit: Integer;
  LValue: UInt32;
begin
  LValue := 0;
  Check(Length(AHex) > 0, 'empty hex codepoint');
  for I := 1 to Length(AHex) do
  begin
    LDigit := ParseHexDigit(AHex[I]);
    Check(LDigit >= 0, 'invalid hex digit in ' + AHex);
    LValue := (LValue shl 4) or UInt32(LDigit);
  end;
  Result := LValue;
end;

function Utf8FromHexField(const AField: string): string;
var
  LStart, I: Integer;
  LToken: string;
begin
  Result := '';
  if AField = '' then
    Exit;
  LStart := 1;
  for I := 1 to Length(AField) + 1 do
  begin
    if (I > Length(AField)) or (AField[I] = ' ') then
    begin
      if I > LStart then
      begin
        LToken := Copy(AField, LStart, I - LStart);
        AppendUtf8(Result, ParseHexCodepoint(LToken));
      end;
      LStart := I + 1;
    end;
  end;
end;

procedure ExpectNorm(const AExpected, AActual, ALabel: string; const ALineNo: Integer);
begin
  if AExpected <> AActual then
    CheckEqual(AExpected, AActual,
      TextFormat('line %d %s', [ALineNo, ALabel]));
end;

procedure TestNormalizationConformance;
var
  LPath: string;
  LFile: Text;
  LLine: string;
  LLineNo: Integer;
  LParts: array[0..4] of string;
  LFieldIdx, LStart, I: Integer;
  LC1, LC2, LC3, LC4, LC5: string;
  LChecked: Integer;
begin
  LPath := ResolveFixture('normalization_test.txt');
  Check(FileExists(LPath), 'fixture exists: ' + LPath);

  Assign(LFile, LPath);
  Reset(LFile);
  LLineNo := 0;
  LChecked := 0;
  try
    while not Eof(LFile) do
    begin
      ReadLn(LFile, LLine);
      Inc(LLineNo);
      if (LLine = '') or (LLine[1] = '#') then
        Continue;

      LFieldIdx := 0;
      LStart := 1;
      for I := 1 to Length(LLine) + 1 do
      begin
        if (I > Length(LLine)) or (LLine[I] = ';') then
        begin
          Check(LFieldIdx <= 4, TextFormat('too many fields line %d', [LLineNo]));
          LParts[LFieldIdx] := Copy(LLine, LStart, I - LStart);
          Inc(LFieldIdx);
          LStart := I + 1;
          if LFieldIdx > 4 then
            Break;
        end;
      end;
      CheckEqual(Int64(5), Int64(LFieldIdx), TextFormat('need 5 fields line %d', [LLineNo]));

      LC1 := Utf8FromHexField(LParts[0]);
      LC2 := Utf8FromHexField(LParts[1]);
      LC3 := Utf8FromHexField(LParts[2]);
      LC4 := Utf8FromHexField(LParts[3]);
      LC5 := Utf8FromHexField(LParts[4]);

      { NFC }
      ExpectNorm(LC2, NFC(LC1), 'NFC(c1)', LLineNo);
      ExpectNorm(LC2, NFC(LC2), 'NFC(c2)', LLineNo);
      ExpectNorm(LC2, NFC(LC3), 'NFC(c3)', LLineNo);
      ExpectNorm(LC4, NFC(LC4), 'NFC(c4)', LLineNo);
      ExpectNorm(LC4, NFC(LC5), 'NFC(c5)', LLineNo);

      { NFD }
      ExpectNorm(LC3, NFD(LC1), 'NFD(c1)', LLineNo);
      ExpectNorm(LC3, NFD(LC2), 'NFD(c2)', LLineNo);
      ExpectNorm(LC3, NFD(LC3), 'NFD(c3)', LLineNo);
      ExpectNorm(LC5, NFD(LC4), 'NFD(c4)', LLineNo);
      ExpectNorm(LC5, NFD(LC5), 'NFD(c5)', LLineNo);

      { NFKC }
      ExpectNorm(LC4, NFKC(LC1), 'NFKC(c1)', LLineNo);
      ExpectNorm(LC4, NFKC(LC2), 'NFKC(c2)', LLineNo);
      ExpectNorm(LC4, NFKC(LC3), 'NFKC(c3)', LLineNo);
      ExpectNorm(LC4, NFKC(LC4), 'NFKC(c4)', LLineNo);
      ExpectNorm(LC4, NFKC(LC5), 'NFKC(c5)', LLineNo);

      { NFKD }
      ExpectNorm(LC5, NFKD(LC1), 'NFKD(c1)', LLineNo);
      ExpectNorm(LC5, NFKD(LC2), 'NFKD(c2)', LLineNo);
      ExpectNorm(LC5, NFKD(LC3), 'NFKD(c3)', LLineNo);
      ExpectNorm(LC5, NFKD(LC4), 'NFKD(c4)', LLineNo);
      ExpectNorm(LC5, NFKD(LC5), 'NFKD(c5)', LLineNo);

      Inc(LChecked);
    end;
  finally
    Close(LFile);
  end;

  Check(LChecked >= 19000, TextFormat('expected ~19965 rows, got %d', [LChecked]));
end;

begin
  T := TTestSuite.Create('nextpas.core.text.unicode.conformance.normalize');
  T.Test('NormalizationTest.txt full suite', @TestNormalizationConformance);
  if not T.Run then
    Halt(1);
end.
