PROGRAM = test_bench_parallel

SRCS = $(PROGRAM).lpr \
       $(SRC_DIR)/nextpas.core.bench.base.pas \
       $(SRC_DIR)/nextpas.core.bench.baseline.pas \
       $(SRC_DIR)/nextpas.core.bench.intf.pas \
       $(SRC_DIR)/nextpas.core.bench.memtrack.pas \
       $(SRC_DIR)/nextpas.core.bench.parallel.pas \
       $(SRC_DIR)/nextpas.core.bench.pas \
       $(SRC_DIR)/nextpas.core.bench.report.pas \
       $(SRC_DIR)/nextpas.core.bench.runner.pas \
       $(SRC_DIR)/nextpas.core.bench.stats.pas \
       $(SRC_DIR)/nextpas.core.bench.stats.advanced.pas \
       $(SRC_DIR)/nextpas.core.bench.xlang.pas \
       $(SRC_DIR)/nextpas.core.sync.mutex.pas

include ../bench_test_common.mk
