.PHONY: test

test:
	./test_build_hygiene_check.sh
	./test_core_focused_makefiles.sh
	./test_landing_candidate_check.sh
	./test_root_focused_gate.sh
	./test_verify_local_failure_truth.sh
	./test_worktree_audit.sh
