.PHONY: test

test:
	./test_build_hygiene_check.sh
	./test_ci_evidence_matrix_doc_contract.sh
	./test_ci_workflow_contract.sh
	./test_core_ci_best_effort_gate.sh
	./test_core_focused_makefiles.sh
	./test_focused_gate_matrix_doc_contract.sh
	./test_lane_focused_gate.sh
	./test_landing_candidate_check.sh
	./test_landing_queue_classifier.sh
	./test_report_envelope_check.sh
	./test_root_focused_gate.sh
	./test_verify_local_compile_truth.sh
	./test_worktrees_doc_contract.sh
	./test_verify_local_failure_truth.sh
	./test_worktree_audit.sh
