unit nextpas.core.git.libgit2.bindings.types;
{$I nextpas.core.settings.inc}
{$PACKRECORDS C}
interface
uses
  nextpas.core.base.utils,
  nextpas.core.git.libgit2.base;

type
  // Scalar C type aliases (lp64) – single source via base for OID
  TTimeT = Int64;
  TGitCertT = LongInt;
  TGitCredentialT = LongInt;
  TSizeT = QWord;
  TGitOidT = LongInt;
  TPtrdiffT = Int64;
  TWcharT = LongInt;
  TXBuiltinVaList = Pointer;
  TClockT = Int64;
  TInt8T = ShortInt;
  TUint8T = Byte;
  TInt16T = SmallInt;
  TUint16T = Word;
  TInt32T = LongInt;
  TUint32T = LongWord;
  TInt64T = Int64;
  TUint64T = QWord;
  TIntptrT = Int64;
  TUintptrT = QWord;
  TIntmaxT = Int64;
  TUintmaxT = QWord;
  TGitFeatureT = LongInt;
  TGitLibgit2OptT = LongInt;
  TGitBuildinfoT = LongInt;
  TSsizeT = Int64;
  TUidT = LongWord;
  TGidT = LongWord;
  TPidT = LongInt;
  TOffT = Int64;
  TInoT = QWord;
  TModeT = LongWord;
  TGitObjectT = LongInt;
  TGitReferenceT = LongInt;
  TGitBranchT = LongInt;
  TGitFilemodeT = LongInt;
  TGitSubmoduleUpdateT = LongInt;
  TGitSubmoduleIgnoreT = LongInt;
  TGitSubmoduleRecurseT = LongInt;
  TGitOdbLookupFlagsT = LongInt;
  TGitReferenceFormatT = LongInt;
  TGitRefdbT = LongInt;
  TGitFilterModeT = LongInt;
  TGitFilterFlagT = LongInt;
  TGitRepositoryOpenFlagT = LongInt;
  TGitRepositoryInitFlagT = LongInt;
  TGitRepositoryInitModeT = LongInt;
  TGitRepositoryItemT = LongInt;
  TGitRepositoryStateT = LongInt;
  TGitTreewalkMode = LongInt;
  TGitTreeUpdateT = LongInt;
  TGitDiffOptionT = LongInt;
  TGitDiffFlagT = LongInt;
  TGitDeltaT = LongInt;
  TGitDiffBinaryT = LongInt;
  TGitDiffLineT = LongInt;
  TGitDiffFindT = LongInt;
  TGitDiffFormatT = LongInt;
  TGitDiffStatsFormatT = LongInt;
  TGitApplyFlagsT = LongInt;
  TGitApplyLocationT = LongInt;
  TGitAttrValueT = LongInt;
  TGitBlobFilterFlagT = LongInt;
  TGitBlameFlagT = LongInt;
  TGitCertSshT = LongInt;
  TGitCertSshRawTypeT = LongInt;
  TGitCheckoutStrategyT = LongInt;
  TGitCheckoutNotifyT = LongInt;
  TGitIndexEntryFlagT = LongInt;
  TGitIndexEntryExtendedFlagT = LongInt;
  TGitIndexCapabilityT = LongInt;
  TGitIndexAddOptionT = LongInt;
  TGitIndexStageT = LongInt;
  TGitMergeFlagT = LongInt;
  TGitMergeFileFavorT = LongInt;
  TGitMergeFileFlagT = LongInt;
  TGitMergeAnalysisT = LongInt;
  TGitMergePreferenceT = LongInt;
  TGitDirection = LongInt;
  TGitPackbuilderStageT = LongInt;
  TGitProxyT = LongInt;
  TGitRemoteRedirectT = LongInt;
  TGitRemoteCreateFlags = LongInt;
  TGitRemoteUpdateFlags = LongInt;
  TGitRemoteCompletionT = LongInt;
  TGitFetchPruneT = LongInt;
  TGitRemoteAutotagOptionT = LongInt;
  TGitFetchDepthT = LongInt;
  TGitCloneLocalT = LongInt;
  TGitConfigLevelT = LongInt;
  TGitConfigmapT = LongInt;
  TGitDescribeStrategyT = LongInt;
  TGitErrorCode = LongInt;
  TGitErrorT = LongInt;
  TGitRebaseOperationT = LongInt;
  TGitTraceLevelT = LongInt;
  TGitRevspecT = LongInt;
  TGitStashFlags = LongInt;
  TGitStashApplyFlags = LongInt;
  TGitStashApplyProgressT = LongInt;
  TGitStatusT = LongInt;
  TGitStatusShowT = LongInt;
  TGitStatusOptT = LongInt;
  TGitSubmoduleStatusT = LongInt;
  TGitWorktreePruneT = LongInt;
  TGitDiffFormatEmailFlagsT = LongInt;
  TGitEmailCreateFlagsT = LongInt;
  TGitOdbBackendLooseFlagT = LongInt;
  TGitOdbStreamT = LongInt;
  TGitPathspecFlagT = LongInt;
  TGitResetT = LongInt;
  TGitSortT = LongInt;
  TGitObjectSizeT = TUint64T;
  TGitOffT = TInt64T;
  TGitTimeT = TInt64T;
  TGitAttrT = TGitAttrValueT;
  TGitRevparseModeT = TGitRevspecT;

implementation
end.
