unit nextpas.core.text.unicode.types;

{$I nextpas.core.settings.inc}

interface

type
  TUnicodeCodepoint = UInt32;

  TGeneralCategory = (
    gcuUppercaseLetter,
    gcuLowercaseLetter,
    gcuTitlecaseLetter,
    gcuModifierLetter,
    gcuOtherLetter,
    gcuNonspacingMark,
    gcuSpacingMark,
    gcuEnclosingMark,
    gcuDecimalNumber,
    gcuLetterNumber,
    gcuOtherNumber,
    gcuConnectorPunctuation,
    gcuDashPunctuation,
    gcuOpenPunctuation,
    gcuClosePunctuation,
    gcuInitialPunctuation,
    gcuFinalPunctuation,
    gcuOtherPunctuation,
    gcuMathSymbol,
    gcuCurrencySymbol,
    gcuModifierSymbol,
    gcuOtherSymbol,
    gcuSpaceSeparator,
    gcuLineSeparator,
    gcuParagraphSeparator,
    gcuControl,
    gcuFormat,
    gcuSurrogate,
    gcuPrivateUse,
    gcuUnassigned
  );

  TBinaryProperty = (
    ubpAlphabetic,
    ubpLowercase,
    ubpUppercase,
    ubpCased,
    ubpCaseIgnorable,
    ubpIdStart,
    ubpIdContinue,
    ubpXidStart,
    ubpXidContinue,
    ubpWhiteSpace,
    ubpGraphemeBase,
    ubpGraphemeExtend,
    ubpMath,
    ubpEmoji,
    ubpEmojiPresentation,
    ubpEmojiModifier,
    ubpEmojiModifierBase,
    ubpEmojiComponent,
    ubpDefaultIgnorableCodePoint,
    ubpDeprecated,
    ubpSoftDotted
  );

  TGeneralCategorySet = set of TGeneralCategory;

  TCodepointRange2 = record
    Lo: TUnicodeCodepoint;
    Hi: TUnicodeCodepoint;
    Delta: Int32;
  end;

  TCodepointRange3 = record
    Lo: TUnicodeCodepoint;
    Hi: TUnicodeCodepoint;
    Value: Byte;
  end;

  TCodepointRange16 = record
    Lo: TUnicodeCodepoint;
    Hi: TUnicodeCodepoint;
    Value: UInt16;
  end;

  TCodepointRange32 = record
    Lo: TUnicodeCodepoint;
    Hi: TUnicodeCodepoint;
    Value: UInt32;
  end;

  TCaseFoldMap = array[0..7] of TUnicodeCodepoint;

  TCaseFoldEntry = record
    Cp: TUnicodeCodepoint;
    Len: Byte;
    Map: TCaseFoldMap;
  end;

  // Script 属性枚举（Unicode 16.0）
  TUnicodeScript = (
    usCommon,
    usLatin,
    usGreek,
    usCyrillic,
    usArmenian,
    usHebrew,
    usArabic,
    usSyriac,
    usThaana,
    usDevanagari,
    usBengali,
    usGurmukhi,
    usGujarati,
    usOriya,
    usTamil,
    usTelugu,
    usKannada,
    usMalayalam,
    usSinhala,
    usThai,
    usLao,
    usTibetan,
    usMyanmar,
    usGeorgian,
    usHangul,
    usEthiopic,
    usCherokee,
    usCanadianAboriginal,
    usOgham,
    usRunic,
    usKhmer,
    usMongolian,
    usHiragana,
    usKatakana,
    usBopomofo,
    usHan,
    usYi,
    usOldItalic,
    usGothic,
    usDeseret,
    usInherited,
    usTagalog,
    usHanunoo,
    usBuhid,
    usTagbanwa,
    usLimbu,
    usTaiLe,
    usLinearB,
    usUgaritic,
    usShavian,
    usOsmanya,
    usCypriot,
    usBraille,
    usBuginese,
    usCoptic,
    usNewTaiLue,
    usGlagolitic,
    usTifinagh,
    usSylotiNagri,
    usOldPersian,
    usKharoshthi,
    usBalinese,
    usCuneiform,
    usPhoenician,
    usPhagsPa,
    usNko,
    usSundanese,
    usLepcha,
    usOlChiki,
    usVai,
    usSaurashtra,
    usKayahLi,
    usRejang,
    usCham,
    usTaiTham,
    usTaiViet,
    usAvestan,
    usEgyptianHieroglyphs,
    usSamaritan,
    usMandaic,
    usLisu,
    usBamum,
    usJavanese,
    usMeeteiMayek,
    usImperialAramaic,
    usOldSouthArabian,
    usInscriptionalParthian,
    usInscriptionalPahlavi,
    usOldTurkic,
    usKaithi,
    usBatak,
    usBrahmi,
    usChakma,
    usMeroiticCursive,
    usMeroiticHieroglyphs,
    usMiao,
    usSharada,
    usSoraSompeng,
    usTakri,
    usCaucasianAlbanian,
    usBassaVah,
    usDuployan,
    usElbasan,
    usGrantha,
    usPahawhHmong,
    usKhojki,
    usLinearA,
    usMahajani,
    usManichaean,
    usMendeKikakui,
    usModi,
    usMro,
    usOldNorthArabian,
    usNabataean,
    usPalmyrene,
    usPauCinHau,
    usOldPermic,
    usPsalterPahlavi,
    usSiddham,
    usKhudawadi,
    usTirhuta,
    usWarangCiti,
    usAhom,
    usAnatolianHieroglyphs,
    usHatran,
    usMultani,
    usOldHungarian,
    usSignWriting,
    usAdlam,
    usBhaiksuki,
    usMarchen,
    usNewa,
    usOsage,
    usTangut,
    usMasaramGondi,
    usNushu,
    usSoyombo,
    usZanabazarSquare,
    usDogra,
    usGunjalaGondi,
    usMakasar,
    usMedefaidrin,
    usOldSogdian,
    usSogdian,
    usChorasmian,
    usElymaic,
    usNandinagari,
    usNyiakengPuachueHmong,
    usWancho,
    usYezidi,
    usCyproMinoan,
    usTangsa,
    usToto,
    usVithkuqi,
    usKawi,
    usNagMundari,
    usTodhri,
    usTuluTigalari,
    usUnknown
  );

  // Grapheme_Cluster_Break 属性枚举（Unicode 16.0, UAX #29）
  TGraphemeBreakProperty = (
    gbpOther,                 // 0
    gbpCR,                    // 1
    gbpLF,                    // 2
    gbpControl,               // 3
    gbpExtend,                // 4
    gbpZWJ,                   // 5
    gbpRegionalIndicator,    // 6
    gbpPrepend,               // 7
    gbpSpacingMark,           // 8
    gbpL,                     // 9  Hangul Jamo Leading
    gbpV,                     // 10 Hangul Jamo Vowel
    gbpT,                     // 11 Hangul Jamo Trailing
    gbpLV,                    // 12 Hangul Syllable LV
    gbpLVT,                   // 13 Hangul Syllable LVT
    gbpExtendedPictographic   // 14
  );

  // Indic_Conjunct_Break (InCB) — Unicode 15.1+ / UAX #29 GB9c
  TIndicConjunctBreak = (
    icbNone = 0,
    icbLinker = 1,
    icbConsonant = 2,
    icbExtend = 3
  );

  // Block 属性枚举（Unicode 16.0）
  TUnicodeBlock = (
    ubBasicLatin,
    ubLatinExtendedA,
    ubLatinExtendedB,
    ubIPAExtensions,
    ubSpacingModifierLetters,
    ubCombiningDiacriticalMarks,
    ubGreekAndCoptic,
    ubCyrillic,
    ubCyrillicSupplement,
    ubArmenian,
    ubHebrew,
    ubArabic,
    ubSyriac,
    ubThaana,
    ubNKo,
    ubSamaritan,
    ubMandaic,
    ubSyriacSupplement,
    ubArabicExtendedB,
    ubArabicExtendedA,
    ubDevanagari,
    ubBengali,
    ubGurmukhi,
    ubGujarati,
    ubOriya,
    ubTamil,
    ubTelugu,
    ubKannada,
    ubMalayalam,
    ubSinhala,
    ubThai,
    ubLao,
    ubTibetan,
    ubMyanmar,
    ubGeorgian,
    ubHangulJamo,
    ubEthiopic,
    ubEthiopicSupplement,
    ubCherokee,
    ubUnifiedCanadianAboriginalSyllabics,
    ubOgham,
    ubRunic,
    ubTagalog,
    ubHanunoo,
    ubBuhid,
    ubTagbanwa,
    ubKhmer,
    ubMongolian,
    ubUnifiedCanadianAboriginalSyllabicsExtended,
    ubLimbu,
    ubTaiLe,
    ubNewTaiLue,
    ubKhmerSymbols,
    ubBuginese,
    ubTaiTham,
    ubCombiningDiacriticalMarksExtended,
    ubBalinese,
    ubSundanese,
    ubBatak,
    ubLepcha,
    ubOlChiki,
    ubCyrillicExtendedC,
    ubGeorgianExtended,
    ubSundaneseSupplement,
    ubVedicExtensions,
    ubPhoneticExtensions,
    ubPhoneticExtensionsSupplement,
    ubCombiningDiacriticalMarksSupplement,
    ubLatinExtendedAdditional,
    ubGreekExtended,
    ubGeneralPunctuation,
    ubSuperscriptsAndSubscripts,
    ubCurrencySymbols,
    ubCombiningDiacriticalMarksforSymbols,
    ubLetterlikeSymbols,
    ubNumberForms,
    ubArrows,
    ubMathematicalOperators,
    ubMiscellaneousTechnical,
    ubControlPictures,
    ubOpticalCharacterRecognition,
    ubEnclosedAlphanumerics,
    ubBoxDrawing,
    ubBlockElements,
    ubGeometricShapes,
    ubMiscellaneousSymbols,
    ubDingbats,
    ubMiscellaneousMathematicalSymbolsA,
    ubSupplementalArrowsA,
    ubBraillePatterns,
    ubSupplementalArrowsB,
    ubMiscellaneousMathematicalSymbolsB,
    ubSupplementalMathematicalOperators,
    ubMiscellaneousSymbolsAndArrows,
    ubGlagolitic,
    ubLatinExtendedC,
    ubCoptic,
    ubGeorgianSupplement,
    ubTifinagh,
    ubEthiopicExtended,
    ubCyrillicExtendedA,
    ubSupplementalPunctuation,
    ubCJKRadicalsSupplement,
    ubKangxiRadicals,
    ubIdeographicDescriptionCharacters,
    ubCJKSymbolsAndPunctuation,
    ubHiragana,
    ubKatakana,
    ubBopomofo,
    ubHangulCompatibilityJamo,
    ubKanbun,
    ubBopomofoExtended,
    ubCJKStrokes,
    ubKatakanaPhoneticExtensions,
    ubEnclosedCJKLettersAndMonths,
    ubCJKCompatibility,
    ubCJKUnifiedIdeographsExtensionA,
    ubYijingHexagramSymbols,
    ubCJKUnifiedIdeographs,
    ubYiSyllables,
    ubYiRadicals,
    ubLisu,
    ubVai,
    ubCyrillicExtendedB,
    ubBamum,
    ubModifierToneLetters,
    ubLatinExtendedD,
    ubSylotiNagri,
    ubCommonIndicNumberForms,
    ubPhagsPa,
    ubSaurashtra,
    ubDevanagariExtended,
    ubKayahLi,
    ubRejang,
    ubHangulJamoExtendedA,
    ubJavanese,
    ubMyanmarExtendedB,
    ubCham,
    ubMyanmarExtendedA,
    ubTaiViet,
    ubMeeteiMayekExtensions,
    ubEthiopicExtendedA,
    ubLatinExtendedE,
    ubCherokeeSupplement,
    ubMeeteiMayek,
    ubHangulSyllables,
    ubHangulJamoExtendedB,
    ubHighSurrogates,
    ubHighPrivateUseSurrogates,
    ubLowSurrogates,
    ubPrivateUseArea,
    ubCJKCompatibilityIdeographs,
    ubAlphabeticPresentationForms,
    ubArabicPresentationFormsA,
    ubVariationSelectors,
    ubVerticalForms,
    ubCombiningHalfMarks,
    ubCJKCompatibilityForms,
    ubSmallFormVariants,
    ubArabicPresentationFormsB,
    ubHalfwidthAndFullwidthForms,
    ubSpecials,
    ubLinearBSyllabary,
    ubLinearBIdeograms,
    ubAegeanNumbers,
    ubAncientGreekNumbers,
    ubAncientSymbols,
    ubPhaistosDisc,
    ubLycian,
    ubCarian,
    ubCopticEpactNumbers,
    ubOldItalic,
    ubGothic,
    ubOldPermic,
    ubUgaritic,
    ubOldPersian,
    ubDeseret,
    ubShavian,
    ubOsmanya,
    ubOsage,
    ubElbasan,
    ubCaucasianAlbanian,
    ubVithkuqi,
    ubLinearA,
    ubLatinExtendedF,
    ubCypriotSyllabary,
    ubImperialAramaic,
    ubPalmyrene,
    ubNabataean,
    ubHatran,
    ubPhoenician,
    ubLydian,
    ubMeroiticHieroglyphs,
    ubMeroiticCursive,
    ubKharoshthi,
    ubOldSouthArabian,
    ubOldNorthArabian,
    ubManichaean,
    ubAvestan,
    ubInscriptionalParthian,
    ubInscriptionalPahlavi,
    ubPsalterPahlavi,
    ubOldTurkic,
    ubOldHungarian,
    ubHanifiRohingya,
    ubRumiNumeralSymbols,
    ubYezidi,
    ubArabicExtendedC,
    ubOldSogdian,
    ubSogdian,
    ubOldUyghur,
    ubChorasmian,
    ubElymaic,
    ubBrahmi,
    ubKaithi,
    ubSoraSompeng,
    ubChakma,
    ubMahajani,
    ubSharada,
    ubSinhalaArchaicNumbers,
    ubKhojki,
    ubMultani,
    ubKhudawadi,
    ubGrantha,
    ubNewa,
    ubTirhuta,
    ubSiddham,
    ubModi,
    ubMongolianSupplement,
    ubTakri,
    ubMyanmarExtendedC,
    ubAhom,
    ubDogra,
    ubNandinagari,
    ubZanabazarSquare,
    ubSoyombo,
    ubUnifiedCanadianAboriginalSyllabicsExtendedA,
    ubPauCinHau,
    ubDevanagariExtendedA,
    ubBhaiksuki,
    ubMarchen,
    ubMasaramGondi,
    ubGunjalaGondi,
    ubMakasar,
    ubKawi,
    ubLisuSupplement,
    ubTamilSupplement,
    ubCuneiform,
    ubCuneiformNumbersAndPunctuation,
    ubEarlyDynasticCuneiform,
    ubCyproMinoan,
    ubEgyptianHieroglyphs,
    ubEgyptianHieroglyphsExtendedA,
    ubAnatolianHieroglyphs,
    ubGurungKhema,
    ubBamumSupplement,
    ubMro,
    ubTangsa,
    ubBassaVah,
    ubPahawhHmong,
    ubMedefaidrin,
    ubMiao,
    ubIdeographicSymbolsAndPunctuation,
    ubTangut,
    ubTangutComponents,
    ubKhitanSmallScript,
    ubTangutSupplement,
    ubKaktovikNumerals,
    ubKatakanaExtended,
    ubKatakanaPhoneticExtensionsSupplement,
    ubCJKUnifiedIdeographsExtensionB,
    ubCJKUnifiedIdeographsExtensionC,
    ubCJKUnifiedIdeographsExtensionD,
    ubCJKUnifiedIdeographsExtensionE,
    ubCJKUnifiedIdeographsExtensionF,
    ubCJKUnifiedIdeographsExtensionI,
    ubCJKCompatibilityIdeographsSupplement,
    ubCJKUnifiedIdeographsExtensionG,
    ubCJKUnifiedIdeographsExtensionH,
    ubTags,
    ubVariationSelectorsSupplement,
    ubSupplementaryPrivateUseAreaA,
    ubSupplementaryPrivateUseAreaB,
    ubNoBlock
  );

const
  UNICODE_MAX_CODEPOINT = TUnicodeCodepoint($10FFFF);
  UNICODE_SURROGATE_FIRST = TUnicodeCodepoint($D800);
  UNICODE_SURROGATE_LAST = TUnicodeCodepoint($DFFF);

implementation

end.