unit nextpas.core.git.libgit2.ffi.consts;

{$I nextpas.core.settings.inc}
// Const domain — all GIT_* error/status/delta/sort/credential/option-version/checkout/worktree constants.
// Zero IFDEF, single source via bindings.consts for drift guard, inline zero-copy not needed.

interface

const
  GIT_OK = 0;
  GIT_ERROR = -1;
  GIT_ENOTFOUND = -3;
  GIT_EEXISTS = -4;
  GIT_EAMBIGUOUS = -5;
  GIT_EBUFS = -6;
  GIT_EUSER = -7;
  GIT_EBAREREPO = -8;
  GIT_EUNBORNBRANCH = -9;
  GIT_EUNMERGED = -10;
  GIT_ENONFASTFORWARD = -11;
  GIT_EINVALIDSPEC = -12;
  GIT_ECONFLICT = -13;
  GIT_ELOCKED = -14;
  GIT_EMODIFIED = -15;
  GIT_EAUTH = -16;
  GIT_ECERTIFICATE = -17;
  GIT_EAPPLIED = -18;
  GIT_EPEEL = -19;
  GIT_EEOF = -20;
  GIT_EINVALID = -21;
  GIT_EUNCOMMITTED = -22;
  GIT_EDIRECTORY = -23;
  GIT_EMERGECONFLICT = -24;
  GIT_PASSTHROUGH = -30;
  GIT_ITEROVER = -31;
  GIT_RETRY = -32;
  GIT_EMISMATCH = -33;
  GIT_EINDEXDIRTY = -34;
  GIT_EAPPLYFAIL = -35;

  GIT_STATUS_CURRENT = 0;
  GIT_STATUS_INDEX_NEW = 1 shl 0;
  GIT_STATUS_INDEX_MODIFIED = 1 shl 1;
  GIT_STATUS_INDEX_DELETED = 1 shl 2;
  GIT_STATUS_INDEX_RENAMED = 1 shl 3;
  GIT_STATUS_INDEX_TYPECHANGE = 1 shl 4;
  GIT_STATUS_WT_NEW = 1 shl 7;
  GIT_STATUS_WT_MODIFIED = 1 shl 8;
  GIT_STATUS_WT_DELETED = 1 shl 9;
  GIT_STATUS_WT_TYPECHANGE = 1 shl 10;
  GIT_STATUS_WT_RENAMED = 1 shl 11;
  GIT_STATUS_WT_UNREADABLE = 1 shl 12;
  GIT_STATUS_IGNORED = 1 shl 14;
  GIT_STATUS_CONFLICTED = 1 shl 15;

  GIT_DELTA_UNMODIFIED = 0;
  GIT_DELTA_ADDED = 1;
  GIT_DELTA_DELETED = 2;
  GIT_DELTA_MODIFIED = 3;
  GIT_DELTA_RENAMED = 4;
  GIT_DELTA_COPIED = 5;
  GIT_DELTA_TYPECHANGE = 6;
  GIT_DELTA_UNREADABLE = 7;
  GIT_DELTA_CONFLICTED = 8;

  GIT_SORT_NONE = 0;
  GIT_SORT_TOPOLOGICAL = 1;
  GIT_SORT_TIME = 2;
  GIT_SORT_REVERSE = 4;

  GIT_CREDENTIAL_USERPASS_PLAINTEXT = 1 shl 0;
  GIT_CREDENTIAL_SSH_KEY = 1 shl 1;
  GIT_CREDENTIAL_SSH_CUSTOM = 1 shl 2;
  GIT_CREDENTIAL_DEFAULT = 1 shl 3;
  GIT_CREDENTIAL_SSH_INTERACTIVE = 1 shl 4;
  GIT_CREDENTIAL_USERNAME = 1 shl 5;
  GIT_CREDENTIAL_SSH_MEMORY = 1 shl 6;

  GIT_REMOTE_CALLBACKS_VERSION = 1;
  GIT_FETCH_OPTIONS_VERSION = 1;
  GIT_PUSH_OPTIONS_VERSION = 1;
  GIT_PROXY_OPTIONS_VERSION = 1;
  GIT_CHECKOUT_OPTIONS_VERSION = 1;
  GIT_CLONE_OPTIONS_VERSION = 1;

  GIT_INDEX_ADD_DEFAULT = 0;
  GIT_INDEX_ADD_FORCE = 1 shl 0;
  GIT_INDEX_ADD_DISABLE_PATHSPEC_MATCH = 1 shl 1;
  GIT_INDEX_ADD_CHECK_PATHSPEC = 1 shl 2;

  GIT_CHECKOUT_SAFE = 0;
  GIT_CHECKOUT_FORCE = 1 shl 1;
  GIT_CHECKOUT_RECREATE_MISSING = 1 shl 2;
  GIT_CHECKOUT_REMOVE_UNTRACKED = 1 shl 5;
  GIT_CHECKOUT_NONE = 1 shl 30;

  GIT_RESET_SOFT = 1;
  GIT_RESET_MIXED = 2;
  GIT_RESET_HARD = 3;

  GIT_WORKTREE_ADD_CREATE_REF = 1 shl 0;
  GIT_WORKTREE_ADD_LOCK = 1 shl 1;
  GIT_WORKTREE_ADD_DETACH = 1 shl 2;

  GIT_WORKTREE_PRUNE_VALID = 1 shl 0;
  GIT_WORKTREE_PRUNE_LOCKED = 1 shl 1;
  GIT_WORKTREE_PRUNE_WORKTREE = 1 shl 2;

  GIT_WORKTREE_ADD_OPTIONS_VERSION = 1;
  GIT_WORKTREE_PRUNE_OPTIONS_VERSION = 1;

  GIT_DIFF_OPTIONS_VERSION = 1;
  GIT_BLAME_OPTIONS_VERSION = 1;

implementation

end.
