unit nextpas.core.text.unicode.types;

{$I nextpas.core.settings.inc}

interface

type
  TUnicodeCodepoint = UInt32;

  TGeneralCategory = (
    gcuUppercaseLetter,
    gcuLowercaseLetter,
    gcuTitlecaseLetter,
    gcuModifierLetter,
    gcuOtherLetter,
    gcuNonspacingMark,
    gcuSpacingMark,
    gcuEnclosingMark,
    gcuDecimalNumber,
    gcuLetterNumber,
    gcuOtherNumber,
    gcuConnectorPunctuation,
    gcuDashPunctuation,
    gcuOpenPunctuation,
    gcuClosePunctuation,
    gcuInitialPunctuation,
    gcuFinalPunctuation,
    gcuOtherPunctuation,
    gcuMathSymbol,
    gcuCurrencySymbol,
    gcuModifierSymbol,
    gcuOtherSymbol,
    gcuSpaceSeparator,
    gcuLineSeparator,
    gcuParagraphSeparator,
    gcuControl,
    gcuFormat,
    gcuSurrogate,
    gcuPrivateUse,
    gcuUnassigned
  );

  TBinaryProperty = (
    ubpAlphabetic,
    ubpLowercase,
    ubpUppercase,
    ubpCased,
    ubpCaseIgnorable,
    ubpIdStart,
    ubpIdContinue,
    ubpXidStart,
    ubpXidContinue,
    ubpWhiteSpace,
    ubpGraphemeBase,
    ubpGraphemeExtend,
    ubpMath,
    ubpEmoji,
    ubpEmojiPresentation,
    ubpEmojiModifier,
    ubpEmojiModifierBase,
    ubpEmojiComponent,
    ubpDefaultIgnorableCodePoint,
    ubpDeprecated,
    ubpSoftDotted
  );

  TGeneralCategorySet = set of TGeneralCategory;

  TCodepointRange2 = record
    Lo: TUnicodeCodepoint;
    Hi: TUnicodeCodepoint;
    Delta: Int32;
  end;

  TCodepointRange3 = record
    Lo: TUnicodeCodepoint;
    Hi: TUnicodeCodepoint;
    Value: Byte;
  end;

  TCodepointRange16 = record
    Lo: TUnicodeCodepoint;
    Hi: TUnicodeCodepoint;
    Value: UInt16;
  end;

  TCodepointRange32 = record
    Lo: TUnicodeCodepoint;
    Hi: TUnicodeCodepoint;
    Value: UInt32;
  end;

  TCaseFoldMap = array[0..7] of TUnicodeCodepoint;

  TCaseFoldEntry = record
    Cp: TUnicodeCodepoint;
    Len: Byte;
    Map: TCaseFoldMap;
  end;

  // Script 属性枚举（Unicode 16.0）
  TUnicodeScript = (
    usCommon,
    usLatin,
    usGreek,
    usCyrillic,
    usArmenian,
    usHebrew,
    usArabic,
    usSyriac,
    usThaana,
    usDevanagari,
    usBengali,
    usGurmukhi,
    usGujarati,
    usOriya,
    usTamil,
    usTelugu,
    usKannada,
    usMalayalam,
    usSinhala,
    usThai,
    usLao,
    usTibetan,
    usMyanmar,
    usGeorgian,
    usHangul,
    usEthiopic,
    usCherokee,
    usCanadianAboriginal,
    usOgham,
    usRunic,
    usKhmer,
    usMongolian,
    usHiragana,
    usKatakana,
    usBopomofo,
    usHan,
    usYi,
    usOldItalic,
    usGothic,
    usDeseret,
    usInherited,
    usTagalog,
    usHanunoo,
    usBuhid,
    usTagbanwa,
    usLimbu,
    usTaiLe,
    usLinearB,
    usUgaritic,
    usShavian,
    usOsmanya,
    usCypriot,
    usBraille,
    usBuginese,
    usCoptic,
    usNewTaiLue,
    usGlagolitic,
    usTifinagh,
    usSylotiNagri,
    usOldPersian,
    usKharoshthi,
    usBalinese,
    usCuneiform,
    usPhoenician,
    usPhagsPa,
    usNko,
    usSundanese,
    usLepcha,
    usOlChiki,
    usVai,
    usSaurashtra,
    usKayahLi,
    usRejang,
    usCham,
    usTaiTham,
    usTaiViet,
    usAvestan,
    usEgyptianHieroglyphs,
    usSamaritan,
    usMandaic,
    usLisu,
    usBamum,
    usJavanese,
    usMeeteiMayek,
    usImperialAramaic,
    usOldSouthArabian,
    usInscriptionalParthian,
    usInscriptionalPahlavi,
    usOldTurkic,
    usKaithi,
    usBatak,
    usBrahmi,
    usChakma,
    usMeroiticCursive,
    usMeroiticHieroglyphs,
    usMiao,
    usSharada,
    usSoraSompeng,
    usTakri,
    usCaucasianAlbanian,
    usBassaVah,
    usDuployan,
    usElbasan,
    usGrantha,
    usPahawhHmong,
    usKhojki,
    usLinearA,
    usMahajani,
    usManichaean,
    usMendeKikakui,
    usModi,
    usMro,
    usOldNorthArabian,
    usNabataean,
    usPalmyrene,
    usPauCinHau,
    usOldPermic,
    usPsalterPahlavi,
    usSiddham,
    usKhudawadi,
    usTirhuta,
    usWarangCiti,
    usAhom,
    usAnatolianHieroglyphs,
    usHatran,
    usMultani,
    usOldHungarian,
    usSignWriting,
    usAdlam,
    usBhaiksuki,
    usMarchen,
    usNewa,
    usOsage,
    usTangut,
    usMasaramGondi,
    usNushu,
    usSoyombo,
    usZanabazarSquare,
    usDogra,
    usGunjalaGondi,
    usMakasar,
    usMedefaidrin,
    usOldSogdian,
    usSogdian,
    usChorasmian,
    usElymaic,
    usNandinagari,
    usNyiakengPuachueHmong,
    usWancho,
    usYezidi,
    usCyproMinoan,
    usTangsa,
    usToto,
    usVithkuqi,
    usKawi,
    usNagMundari,
    usTodhri,
    usTuluTigalari,
    usUnknown
  );

  // Grapheme_Cluster_Break 属性枚举（Unicode 16.0, UAX #29）
  TGraphemeBreakProperty = (
    gbpOther,                 // 0
    gbpCR,                    // 1
    gbpLF,                    // 2
    gbpControl,               // 3
    gbpExtend,                // 4
    gbpZWJ,                   // 5
    gbpRegionalIndicator,    // 6
    gbpPrepend,               // 7
    gbpSpacingMark,           // 8
    gbpL,                     // 9  Hangul Jamo Leading
    gbpV,                     // 10 Hangul Jamo Vowel
    gbpT,                     // 11 Hangul Jamo Trailing
    gbpLV,                    // 12 Hangul Syllable LV
    gbpLVT,                   // 13 Hangul Syllable LVT
    gbpExtendedPictographic   // 14
  );

  // Indic_Conjunct_Break (InCB) — Unicode 15.1+ / UAX #29 GB9c
  TIndicConjunctBreak = (
    icbNone = 0,
    icbLinker = 1,
    icbConsonant = 2,
    icbExtend = 3
  );

  // Word_Break property (Unicode 16.0, UAX #29)
  TWordBreakProperty = (
    wbpOther = 0,
    wbpCR = 1,
    wbpLF = 2,
    wbpNewline = 3,
    wbpExtend = 4,
    wbpZWJ = 5,
    wbpRegionalIndicator = 6,
    wbpFormat = 7,
    wbpKatakana = 8,
    wbpHebrewLetter = 9,
    wbpALetter = 10,
    wbpSingleQuote = 11,
    wbpDoubleQuote = 12,
    wbpMidNumLet = 13,
    wbpMidLetter = 14,
    wbpMidNum = 15,
    wbpNumeric = 16,
    wbpExtendNumLet = 17,
    wbpWSegSpace = 18
  );

  // Sentence_Break property (Unicode 16.0, UAX #29)
  TSentenceBreakProperty = (
    sbpOther = 0,
    sbpCR = 1,
    sbpLF = 2,
    sbpExtend = 3,
    sbpSep = 4,
    sbpFormat = 5,
    sbpSp = 6,
    sbpLower = 7,
    sbpUpper = 8,
    sbpOLetter = 9,
    sbpNumeric = 10,
    sbpATerm = 11,
    sbpSContinue = 12,
    sbpSTerm = 13,
    sbpClose = 14
  );

  // Line_Break class (Unicode 16.0, UAX #14)
  // Ordinals 1..33 match pair-table order OP..CB; 0=XX; 34+ non-table / U16.
  TLineBreakClass = (
    lbcXX = 0,
    lbcOP = 1,
    lbcCL = 2,
    lbcCP = 3,
    lbcQU = 4,
    lbcGL = 5,
    lbcNS = 6,
    lbcEX = 7,
    lbcSY = 8,
    lbcIS = 9,
    lbcPR = 10,
    lbcPO = 11,
    lbcNU = 12,
    lbcAL = 13,
    lbcHL = 14,
    lbcID = 15,
    lbcIN = 16,
    lbcHY = 17,
    lbcBA = 18,
    lbcBB = 19,
    lbcB2 = 20,
    lbcZW = 21,
    lbcCM = 22,
    lbcWJ = 23,
    lbcH2 = 24,
    lbcH3 = 25,
    lbcJL = 26,
    lbcJV = 27,
    lbcJT = 28,
    lbcRI = 29,
    lbcEB = 30,
    lbcEM = 31,
    lbcZWJ = 32,
    lbcCB = 33,
    lbcAI = 34,
    lbcBK = 35,
    lbcCJ = 36,
    lbcCR = 37,
    lbcLF = 38,
    lbcNL = 39,
    lbcSA = 40,
    lbcSG = 41,
    lbcSP = 42,
    lbcAK = 43,
    lbcAP = 44,
    lbcAS = 45,
    lbcVF = 46,
    lbcVI = 47
  );

  // Bidi_Class (Unicode 16.0, UAX #9)
  TBidiClass = (
    bcL = 0,
    bcR = 1,
    bcEN = 2,
    bcES = 3,
    bcET = 4,
    bcAN = 5,
    bcCS = 6,
    bcB = 7,
    bcS = 8,
    bcWS = 9,
    bcON = 10,
    bcBN = 11,
    bcNSM = 12,
    bcAL = 13,
    bcLRE = 14,
    bcLRO = 15,
    bcRLE = 16,
    bcRLO = 17,
    bcPDF = 18,
    bcLRI = 19,
    bcRLI = 20,
    bcFSI = 21,
    bcPDI = 22
  );

  // Bidi_Paired_Bracket_Type
  TBidiPairedBracketType = (
    bpbtNone = 0,
    bpbtOpen = 1,
    bpbtClose = 2
  );

  // Block 属性枚举（Unicode 16.0）
  TUnicodeBlock = (
    ubBasicLatin,
    ubLatinExtendedA,
    ubLatinExtendedB,
    ubIPAExtensions,
    ubSpacingModifierLetters,
    ubCombiningDiacriticalMarks,
    ubGreekAndCoptic,
    ubCyrillic,
    ubCyrillicSupplement,
    ubArmenian,
    ubHebrew,
    ubArabic,
    ubSyriac,
    ubThaana,
    ubNKo,
    ubSamaritan,
    ubMandaic,
    ubSyriacSupplement,
    ubArabicExtendedB,
    ubArabicExtendedA,
    ubDevanagari,
    ubBengali,
    ubGurmukhi,
    ubGujarati,
    ubOriya,
    ubTamil,
    ubTelugu,
    ubKannada,
    ubMalayalam,
    ubSinhala,
    ubThai,
    ubLao,
    ubTibetan,
    ubMyanmar,
    ubGeorgian,
    ubHangulJamo,
    ubEthiopic,
    ubEthiopicSupplement,
    ubCherokee,
    ubUnifiedCanadianAboriginalSyllabics,
    ubOgham,
    ubRunic,
    ubTagalog,
    ubHanunoo,
    ubBuhid,
    ubTagbanwa,
    ubKhmer,
    ubMongolian,
    ubUnifiedCanadianAboriginalSyllabicsExtended,
    ubLimbu,
    ubTaiLe,
    ubNewTaiLue,
    ubKhmerSymbols,
    ubBuginese,
    ubTaiTham,
    ubCombiningDiacriticalMarksExtended,
    ubBalinese,
    ubSundanese,
    ubBatak,
    ubLepcha,
    ubOlChiki,
    ubCyrillicExtendedC,
    ubGeorgianExtended,
    ubSundaneseSupplement,
    ubVedicExtensions,
    ubPhoneticExtensions,
    ubPhoneticExtensionsSupplement,
    ubCombiningDiacriticalMarksSupplement,
    ubLatinExtendedAdditional,
    ubGreekExtended,
    ubGeneralPunctuation,
    ubSuperscriptsAndSubscripts,
    ubCurrencySymbols,
    ubCombiningDiacriticalMarksforSymbols,
    ubLetterlikeSymbols,
    ubNumberForms,
    ubArrows,
    ubMathematicalOperators,
    ubMiscellaneousTechnical,
    ubControlPictures,
    ubOpticalCharacterRecognition,
    ubEnclosedAlphanumerics,
    ubBoxDrawing,
    ubBlockElements,
    ubGeometricShapes,
    ubMiscellaneousSymbols,
    ubDingbats,
    ubMiscellaneousMathematicalSymbolsA,
    ubSupplementalArrowsA,
    ubBraillePatterns,
    ubSupplementalArrowsB,
    ubMiscellaneousMathematicalSymbolsB,
    ubSupplementalMathematicalOperators,
    ubMiscellaneousSymbolsAndArrows,
    ubGlagolitic,
    ubLatinExtendedC,
    ubCoptic,
    ubGeorgianSupplement,
    ubTifinagh,
    ubEthiopicExtended,
    ubCyrillicExtendedA,
    ubSupplementalPunctuation,
    ubCJKRadicalsSupplement,
    ubKangxiRadicals,
    ubIdeographicDescriptionCharacters,
    ubCJKSymbolsAndPunctuation,
    ubHiragana,
    ubKatakana,
    ubBopomofo,
    ubHangulCompatibilityJamo,
    ubKanbun,
    ubBopomofoExtended,
    ubCJKStrokes,
    ubKatakanaPhoneticExtensions,
    ubEnclosedCJKLettersAndMonths,
    ubCJKCompatibility,
    ubCJKUnifiedIdeographsExtensionA,
    ubYijingHexagramSymbols,
    ubCJKUnifiedIdeographs,
    ubYiSyllables,
    ubYiRadicals,
    ubLisu,
    ubVai,
    ubCyrillicExtendedB,
    ubBamum,
    ubModifierToneLetters,
    ubLatinExtendedD,
    ubSylotiNagri,
    ubCommonIndicNumberForms,
    ubPhagsPa,
    ubSaurashtra,
    ubDevanagariExtended,
    ubKayahLi,
    ubRejang,
    ubHangulJamoExtendedA,
    ubJavanese,
    ubMyanmarExtendedB,
    ubCham,
    ubMyanmarExtendedA,
    ubTaiViet,
    ubMeeteiMayekExtensions,
    ubEthiopicExtendedA,
    ubLatinExtendedE,
    ubCherokeeSupplement,
    ubMeeteiMayek,
    ubHangulSyllables,
    ubHangulJamoExtendedB,
    ubHighSurrogates,
    ubHighPrivateUseSurrogates,
    ubLowSurrogates,
    ubPrivateUseArea,
    ubCJKCompatibilityIdeographs,
    ubAlphabeticPresentationForms,
    ubArabicPresentationFormsA,
    ubVariationSelectors,
    ubVerticalForms,
    ubCombiningHalfMarks,
    ubCJKCompatibilityForms,
    ubSmallFormVariants,
    ubArabicPresentationFormsB,
    ubHalfwidthAndFullwidthForms,
    ubSpecials,
    ubLinearBSyllabary,
    ubLinearBIdeograms,
    ubAegeanNumbers,
    ubAncientGreekNumbers,
    ubAncientSymbols,
    ubPhaistosDisc,
    ubLycian,
    ubCarian,
    ubCopticEpactNumbers,
    ubOldItalic,
    ubGothic,
    ubOldPermic,
    ubUgaritic,
    ubOldPersian,
    ubDeseret,
    ubShavian,
    ubOsmanya,
    ubOsage,
    ubElbasan,
    ubCaucasianAlbanian,
    ubVithkuqi,
    ubLinearA,
    ubLatinExtendedF,
    ubCypriotSyllabary,
    ubImperialAramaic,
    ubPalmyrene,
    ubNabataean,
    ubHatran,
    ubPhoenician,
    ubLydian,
    ubMeroiticHieroglyphs,
    ubMeroiticCursive,
    ubKharoshthi,
    ubOldSouthArabian,
    ubOldNorthArabian,
    ubManichaean,
    ubAvestan,
    ubInscriptionalParthian,
    ubInscriptionalPahlavi,
    ubPsalterPahlavi,
    ubOldTurkic,
    ubOldHungarian,
    ubHanifiRohingya,
    ubRumiNumeralSymbols,
    ubYezidi,
    ubArabicExtendedC,
    ubOldSogdian,
    ubSogdian,
    ubOldUyghur,
    ubChorasmian,
    ubElymaic,
    ubBrahmi,
    ubKaithi,
    ubSoraSompeng,
    ubChakma,
    ubMahajani,
    ubSharada,
    ubSinhalaArchaicNumbers,
    ubKhojki,
    ubMultani,
    ubKhudawadi,
    ubGrantha,
    ubNewa,
    ubTirhuta,
    ubSiddham,
    ubModi,
    ubMongolianSupplement,
    ubTakri,
    ubMyanmarExtendedC,
    ubAhom,
    ubDogra,
    ubNandinagari,
    ubZanabazarSquare,
    ubSoyombo,
    ubUnifiedCanadianAboriginalSyllabicsExtendedA,
    ubPauCinHau,
    ubDevanagariExtendedA,
    ubBhaiksuki,
    ubMarchen,
    ubMasaramGondi,
    ubGunjalaGondi,
    ubMakasar,
    ubKawi,
    ubLisuSupplement,
    ubTamilSupplement,
    ubCuneiform,
    ubCuneiformNumbersAndPunctuation,
    ubEarlyDynasticCuneiform,
    ubCyproMinoan,
    ubEgyptianHieroglyphs,
    ubEgyptianHieroglyphsExtendedA,
    ubAnatolianHieroglyphs,
    ubGurungKhema,
    ubBamumSupplement,
    ubMro,
    ubTangsa,
    ubBassaVah,
    ubPahawhHmong,
    ubMedefaidrin,
    ubMiao,
    ubIdeographicSymbolsAndPunctuation,
    ubTangut,
    ubTangutComponents,
    ubKhitanSmallScript,
    ubTangutSupplement,
    ubKaktovikNumerals,
    ubKatakanaExtended,
    ubKatakanaPhoneticExtensionsSupplement,
    ubCJKUnifiedIdeographsExtensionB,
    ubCJKUnifiedIdeographsExtensionC,
    ubCJKUnifiedIdeographsExtensionD,
    ubCJKUnifiedIdeographsExtensionE,
    ubCJKUnifiedIdeographsExtensionF,
    ubCJKUnifiedIdeographsExtensionI,
    ubCJKCompatibilityIdeographsSupplement,
    ubCJKUnifiedIdeographsExtensionG,
    ubCJKUnifiedIdeographsExtensionH,
    ubTags,
    ubVariationSelectorsSupplement,
    ubSupplementaryPrivateUseAreaA,
    ubSupplementaryPrivateUseAreaB,
    ubNoBlock
  );

const
  UNICODE_MAX_CODEPOINT = TUnicodeCodepoint($10FFFF);
  UNICODE_SURROGATE_FIRST = TUnicodeCodepoint($D800);
  UNICODE_SURROGATE_LAST = TUnicodeCodepoint($DFFF);

implementation

end.