program test_conformance_sentence;
{**
 * Unicode 16.0 SentenceBreakTest official conformance harness.
 *
 * Fixture: ../data/sentence_break_test.txt
 * Generated by: core/scripts/gen_unicode_fixtures.py
 *
 * Verifies SentenceBreakByteLen against official break opportunities.
 *}

{$I nextpas.core.settings.inc}

uses
  SysUtils,
  nextpas.core.test,
  nextpas.core.text.utf8,
  nextpas.core.text.unicode.base,
  nextpas.core.text.unicode.types,
  nextpas.core.text.unicode;

var
  T: TTestSuite;

{$I ../test_helpers.inc}

function ResolveFixture(const AName: string): string;
begin
  if FileExists('../data/' + AName) then
    Exit('../data/' + AName);
  if FileExists('core/tests/nextpas.core.text.unicode/data/' + AName) then
    Exit('core/tests/nextpas.core.text.unicode/data/' + AName);
  if FileExists('../../nextpas.core.text.unicode/data/' + AName) then
    Exit('../../nextpas.core.text.unicode/data/' + AName);
  Result := '../data/' + AName;
end;

function ParseHexDigit(const ACh: Char): Integer;
begin
  case ACh of
    '0'..'9': Result := Ord(ACh) - Ord('0');
    'a'..'f': Result := Ord(ACh) - Ord('a') + 10;
    'A'..'F': Result := Ord(ACh) - Ord('A') + 10;
  else
    Result := -1;
  end;
end;

function ParseHexCodepoint(const AHex: string): TUnicodeCodepoint;
var
  I: Integer;
  LDigit: Integer;
  LValue: UInt32;
begin
  LValue := 0;
  Check(Length(AHex) > 0, 'empty hex codepoint');
  for I := 1 to Length(AHex) do
  begin
    LDigit := ParseHexDigit(AHex[I]);
    Check(LDigit >= 0, 'invalid hex digit in ' + AHex);
    LValue := (LValue shl 4) or UInt32(LDigit);
  end;
  Result := LValue;
end;

procedure ParseCpList(const AField: string; out ACps: array of TUnicodeCodepoint; out ACount: Integer);
var
  LStart, I: Integer;
  LToken: string;
begin
  ACount := 0;
  if AField = '' then
    Exit;
  LStart := 1;
  for I := 1 to Length(AField) + 1 do
  begin
    if (I > Length(AField)) or (AField[I] = ' ') then
    begin
      if I > LStart then
      begin
        LToken := Copy(AField, LStart, I - LStart);
        Check(ACount < Length(ACps), 'cp list overflow');
        ACps[ACount] := ParseHexCodepoint(LToken);
        Inc(ACount);
      end;
      LStart := I + 1;
    end;
  end;
end;

procedure ParseBreakFlags(const AField: string; out AFlags: array of Byte; out ACount: Integer);
var
  LStart, I: Integer;
  LToken: string;
begin
  ACount := 0;
  LStart := 1;
  for I := 1 to Length(AField) + 1 do
  begin
    if (I > Length(AField)) or (AField[I] = ' ') then
    begin
      if I > LStart then
      begin
        LToken := Copy(AField, LStart, I - LStart);
        Check(ACount < Length(AFlags), 'break flag overflow');
        if LToken = '1' then
          AFlags[ACount] := 1
        else
        begin
          Check(LToken = '0', 'break flag must be 0/1');
          AFlags[ACount] := 0;
        end;
        Inc(ACount);
      end;
      LStart := I + 1;
    end;
  end;
end;

function BuildUtf8(const ACps: array of TUnicodeCodepoint; const ACount: Integer): string;
var
  I: Integer;
begin
  Result := '';
  for I := 0 to ACount - 1 do
    AppendUtf8(Result, ACps[I]);
end;

procedure ObservedSentenceBreaks(
  const AText: string;
  const ACpCount: Integer;
  out AFlags: array of Byte);
var
  LPos, LEnd, LCpIdx: SizeInt;
  LBytes: SizeUInt;
  LDecode: TUTF8DecodeResult;
  I: Integer;
  LSegEnd: SizeInt;
begin
  for I := 0 to ACpCount do
    AFlags[I] := 0;
  if ACpCount = 0 then
  begin
    AFlags[0] := 1;
    Exit;
  end;

  AFlags[0] := 1;
  AFlags[ACpCount] := 1;

  LPos := 1;
  LEnd := Length(AText);
  LCpIdx := 0;
  while LPos <= LEnd do
  begin
    LBytes := SentenceBreakByteLen(@AText[LPos], SizeUInt(LEnd - LPos + 1));
    if LBytes = 0 then
      Break;
    LSegEnd := LPos + SizeInt(LBytes);
    while LPos < LSegEnd do
    begin
      LDecode := UTF8Decode(@AText[LPos], LEnd - LPos + 1);
      if LDecode.ByteLen = 0 then
      begin
        Inc(LPos);
        Inc(LCpIdx);
      end
      else
      begin
        Inc(LPos, LDecode.ByteLen);
        Inc(LCpIdx);
      end;
    end;
    if (LCpIdx > 0) and (LCpIdx < ACpCount) then
      AFlags[LCpIdx] := 1;
  end;
end;

procedure TestSentenceBreakConformance;
var
  LPath: string;
  LFile: Text;
  LLine: string;
  LLineNo, LChecked, LPipe: Integer;
  LCps: array[0..127] of TUnicodeCodepoint;
  LExp, LObs: array[0..128] of Byte;
  LCpCount, LFlagCount, I: Integer;
  LText: string;
  LExpStr, LObsStr: string;
begin
  LPath := ResolveFixture('sentence_break_test.txt');
  Check(FileExists(LPath), 'fixture exists: ' + LPath);

  Assign(LFile, LPath);
  Reset(LFile);
  LLineNo := 0;
  LChecked := 0;
  try
    while not Eof(LFile) do
    begin
      ReadLn(LFile, LLine);
      Inc(LLineNo);
      if (LLine = '') or (LLine[1] = '#') then
        Continue;

      LPipe := Pos('|', LLine);
      Check(LPipe > 0, Format('missing | line %d', [LLineNo]));

      ParseCpList(Copy(LLine, 1, LPipe - 1), LCps, LCpCount);
      ParseBreakFlags(Copy(LLine, LPipe + 1, MaxInt), LExp, LFlagCount);
      CheckEqual(Int64(LCpCount + 1), Int64(LFlagCount),
        Format('flag count line %d', [LLineNo]));

      LText := BuildUtf8(LCps, LCpCount);
      ObservedSentenceBreaks(LText, LCpCount, LObs);

      LExpStr := '';
      LObsStr := '';
      for I := 0 to LCpCount do
      begin
        if I > 0 then
        begin
          LExpStr := LExpStr + ' ';
          LObsStr := LObsStr + ' ';
        end;
        if LExp[I] <> 0 then
          LExpStr := LExpStr + '1'
        else
          LExpStr := LExpStr + '0';
        if LObs[I] <> 0 then
          LObsStr := LObsStr + '1'
        else
          LObsStr := LObsStr + '0';
      end;

      if LExpStr <> LObsStr then
        CheckEqual(LExpStr, LObsStr,
          Format('line %d cps=%s', [LLineNo, Copy(LLine, 1, LPipe - 1)]));

      Inc(LChecked);
    end;
  finally
    Close(LFile);
  end;

  Check(LChecked >= 400, Format('expected many sentence rows, got %d', [LChecked]));
end;

begin
  T := TTestSuite.Create('nextpas.core.text.unicode.conformance.sentence');
  T.Test('SentenceBreakTest.txt full suite', @TestSentenceBreakConformance);
  if not T.Run then
    Halt(1);
end.
