"""
simdgen_neon - NEON (AArch64) batch kernel code generator

Generates Pascal asm code for NEON batch array operations from
the same batch.json definitions used by AVX2/SSE2 generators.

NEON specifics:
- 128-bit SIMD registers (v0-v31), 4 floats per register
- Instructions: fadd v0.4s, v0.4s, v1.4s
- No vzeroupper equivalent needed
- 4x register unroll = 16 elements per main loop iteration
"""

import json
from pathlib import Path
from typing import Any


def mem(reg: str, offset: int = 0) -> str:
    if offset == 0:
        return f"[{reg}]"
    return f"[{reg}, #{offset}]"


def asm_line(opcode: str, operands: str = "") -> str:
    return f"    {opcode}" if operands == "" else f"    {opcode} {operands}"


NEON_VEC_MAP = {
    "vaddps": "fadd",
    "vsubps": "fsub",
    "vmulps": "fmul",
    "vdivps": "fdiv",
    "vminps": "fmin",
    "vmaxps": "fmax",
    "vsqrtps": "fsqrt",
}

NEON_SUFFIX = ".4s"


def neon_vec(avx2_op: str) -> str:
    return NEON_VEC_MAP.get(avx2_op, avx2_op)


def emit_neon_elementwise_2input(op: dict) -> list[str]:
    """Generate NEON elementwise kernel with 2 input streams."""
    tpl = op["avx2_template"]
    inputs = tpl["streams"]["inputs"]
    output = tpl["streams"]["output"]
    neon_op = neon_vec(tpl["steps"][0]["vector"])

    lines = [
        f'procedure NEON{op["name"]}({inputs[0]["param"]}, {inputs[1]["param"]}, {output["param"]}: PSingle; aCount: SizeUInt);',
        "var",
        f'  pS1, pS2, pD: PSingle;',
        "begin",
        "  {$PUSH}{$Q-}{$R-}",
        "  if aCount = 0 then Exit;",
        f'  pS1 := {inputs[0]["param"]}; pS2 := {inputs[1]["param"]}; pD := {output["param"]};',
        "",
        "  asm",
        asm_line("ldr", "x0, pS1"),
        asm_line("ldr", "x1, pS2"),
        asm_line("ldr", "x2, pD"),
        asm_line("ldr", "x3, aCount"),
        "",
        asm_line("cmp", "x3, #16"),
        asm_line("b.lo", ".Ltail4"),
        "",
        "  .Lloop16:",
    ]
    for i in range(4):
        off = i * 16
        lines.append(asm_line("ldr", f"q{i}, [x0, #{off}]"))
    for i in range(4):
        off = i * 16
        lines.append(asm_line("ldr", f"q{i+4}, [x1, #{off}]"))
    for i in range(4):
        lines.append(asm_line(f"{neon_op}", f"v{i}{NEON_SUFFIX}, v{i}{NEON_SUFFIX}, v{i+4}{NEON_SUFFIX}"))
    for i in range(4):
        off = i * 16
        lines.append(asm_line("str", f"q{i}, [x2, #{off}]"))
    lines += [
        asm_line("add", "x0, x0, #64"),
        asm_line("add", "x1, x1, #64"),
        asm_line("add", "x2, x2, #64"),
        asm_line("sub", "x3, x3, #16"),
        asm_line("cmp", "x3, #16"),
        asm_line("b.hs", ".Lloop16"),
        "",
        "  .Ltail4:",
        asm_line("cmp", "x3, #4"),
        asm_line("b.lo", ".Ltail_scalar"),
        asm_line("ldr", "q0, [x0]"),
        asm_line("ldr", "q1, [x1]"),
        asm_line(f"{neon_op}", f"v0{NEON_SUFFIX}, v0{NEON_SUFFIX}, v1{NEON_SUFFIX}"),
        asm_line("str", "q0, [x2]"),
        asm_line("add", "x0, x0, #16"),
        asm_line("add", "x1, x1, #16"),
        asm_line("add", "x2, x2, #16"),
        asm_line("sub", "x3, x3, #4"),
        asm_line("cmp", "x3, #4"),
        asm_line("b.hs", ".Ltail4"),
        "",
        "  .Ltail_scalar:",
        asm_line("cbz", "x3, .Ldone"),
        "  .Lscalar_loop:",
        asm_line("ldr", "s0, [x0], #4"),
        asm_line("ldr", "s1, [x1], #4"),
        asm_line(f"f{neon_op[1:]}" if neon_op.startswith("f") else neon_op, "s0, s0, s1"),
        asm_line("str", "s0, [x2], #4"),
        asm_line("subs", "x3, x3, #1"),
        asm_line("b.ne", ".Lscalar_loop"),
        "",
        "  .Ldone:",
        "  end;",
        "  {$POP}",
        "end;",
    ]
    return lines


def generate_neon_batch_kernel(op: dict) -> str | None:
    """Generate NEON kernel for a single operation."""
    tpl = op.get("avx2_template")
    if not tpl:
        return None
    kind = tpl["kind"]
    if kind == "elementwise" and tpl["input_stream_count"] == 2:
        lines = emit_neon_elementwise_2input(op)
        return "\n".join(lines)
    return None


def load_ops() -> list[dict]:
    ops_path = Path(__file__).parent / "ops" / "batch.json"
    with open(ops_path) as f:
        data = json.load(f)
    return data["operations"]


def generate_all_neon() -> str:
    """Generate all supported NEON batch kernels."""
    ops = load_ops()
    sections = []
    generated = 0
    for op in ops:
        code = generate_neon_batch_kernel(op)
        if code:
            sections.append(code)
            generated += 1
    header = (
        f"// Auto-generated NEON (AArch64) batch kernels ({generated} operations)\n"
        f"// Generated by simdgen_neon.py\n"
        f"// Target: ARMv8-A NEON, 128-bit SIMD (4x float32 per register)\n"
    )
    return header + "\n\n".join(sections)


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "--generate":
        print(generate_all_neon())
    elif len(sys.argv) > 1 and sys.argv[1] == "--output":
        output_path = Path(__file__).parent.parent.parent / "src" / "generated" / "nextpas.core.simd.neon.batch.generated.inc"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        code = generate_all_neon()
        output_path.write_text(code)
        ops = load_ops()
        supported = sum(1 for op in ops if generate_neon_batch_kernel(op))
        print(f"Generated {supported} NEON kernels → {output_path}")
    else:
        ops = load_ops()
        supported = sum(1 for op in ops if generate_neon_batch_kernel(op))
        print(f"NEON batch generator: {supported}/{len(ops)} operations supported")
