#!/usr/bin/env python3
"""
simdgen - SIMD dispatch code generator for nextpas.core.simd

Generates Pascal include files from JSON operation definitions.
Zero external dependencies (uses only Python stdlib).

Usage:
    python3 tools/simdgen/simdgen.py [--verify] [--dry-run] [--audit]

Options:
    --verify   Compare canonical generated output against existing code
    --dry-run  Print what would be generated without writing files
    --audit    Compare generated dispatch slots against the live dispatch table
"""

import json
import os
import re
import sys
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
OPS_DIR = SCRIPT_DIR / "ops"
OUTPUT_DIR = PROJECT_ROOT / "src" / "generated"

HEADER = """\
{
  This file is AUTO-GENERATED by tools/simdgen/simdgen.py
  DO NOT EDIT MANUALLY - changes will be overwritten.

  Source definitions: tools/simdgen/ops/
  Regenerate: python3 tools/simdgen/simdgen.py
}
"""

NO_TYPE_SIGNATURES = {
    "psingle_count_single",
    "psingle_psingle_count_single",
    "pointer_len_bool",
    "pointer_len_uint64",
    "pointer_len_sizeuint",
    "pointer_len_byte_sizeuint",
    "pointer_len_byte_ptrint",
    "pointer_ptr_len_bool",
    "pointer_ptr_len_longbool",
    "pointer_ptr_len_out_sizeuint_out_sizeuint_bool",
    "pointer_len_out_byte_byte_void",
    "pointer_len_ptr_len_ptrint",
    "pointer_len_void",
    "pointer_len_byte_void",
    "pointer_ptr_len_void",
    "psingle_psingle_psingle_count_void",
    "psingle_psingle_count_single_void",
    "single_psingle_psingle_psingle_count_void",
}

POINTER_LEN_RESULT_TYPES = {
    "pointer_len_bool": "Boolean",
    "pointer_len_uint64": "UInt64",
    "pointer_len_sizeuint": "SizeUInt",
}

POINTER_LEN_BYTE_RESULT_TYPES = {
    "pointer_len_byte_sizeuint": "SizeUInt",
    "pointer_len_byte_ptrint": "PtrInt",
}

POINTER_PTR_LEN_RESULT_TYPES = {
    "pointer_ptr_len_bool": "Boolean",
    "pointer_ptr_len_longbool": "LongBool",
}

POINTER_PTR_LEN_OUT_RESULT_TYPES = {
    "pointer_ptr_len_out_sizeuint_out_sizeuint_bool": "Boolean",
}

POINTER_LEN_PTR_LEN_RESULT_TYPES = {
    "pointer_len_ptr_len_ptrint": "PtrInt",
}

POINTER_LEN_VOID_SIGNATURES = {
    "pointer_len_void",
}

POINTER_LEN_BYTE_VOID_SIGNATURES = {
    "pointer_len_byte_void",
}

POINTER_LEN_OUT_BYTE_VOID_SIGNATURES = {
    "pointer_len_out_byte_byte_void",
}

POINTER_PTR_LEN_VOID_SIGNATURES = {
    "pointer_ptr_len_void",
}


# =============================================================================
# Data model
# =============================================================================

@dataclass
class TypeInfo:
    name: str
    vec_type: str
    scalar_type: str
    field_name: str
    lanes: int
    width: int
    mask_type: str
    ptr_type: str
    category: str
    decompose: Optional[list] = None


@dataclass
class Operation:
    name: str
    signature: str
    scalar_op: str
    doc: str
    applies_to: list
    scalar_body: Optional[any] = None
    scalar_vars: Optional[list] = None
    scalar_body_by_type: Optional[dict] = None
    scalar_vars_by_type: Optional[dict] = None
    mask_type_by_type: Optional[dict] = None
    name_pattern: Optional[str] = None
    facade_name_pattern: Optional[str] = None
    scalar_name_pattern: Optional[str] = None
    category: str = ""


@dataclass
class SlotEntry:
    """A single dispatch table slot = operation + type"""
    op: Operation
    type_info: Optional[TypeInfo]

    @property
    def base_name(self) -> str:
        type_name = self.type_info.name if self.type_info else ""
        if self.op.name_pattern:
            return self.op.name_pattern.format(op=self.op.name, type=type_name)
        if self.type_info is None:
            return self.op.name
        return f"{self.op.name}{self.type_info.name}"

    @property
    def dispatch_field(self) -> str:
        return self.base_name

    @property
    def facade_name(self) -> str:
        type_name = self.type_info.name if self.type_info else ""
        if self.op.facade_name_pattern:
            return self.op.facade_name_pattern.format(op=self.op.name, type=type_name)
        if self.type_info is None:
            return self.base_name
        if self.op.name_pattern:
            return self.base_name
        return f"Vec{self.type_info.name}{self.op.name}"

    @property
    def scalar_name(self) -> str:
        type_name = self.type_info.name if self.type_info else ""
        if self.op.scalar_name_pattern:
            return self.op.scalar_name_pattern.format(op=self.op.name, type=type_name, base=self.base_name)
        return f"Scalar{self.base_name}"


# =============================================================================
# Registry: load types and operations from JSON
# =============================================================================

class Registry:
    def __init__(self):
        self.types: dict[str, TypeInfo] = {}
        self.operations: list[Operation] = []
        self.slots: list[SlotEntry] = []

    def load_types(self, path: Path):
        with open(path) as f:
            data = json.load(f)
        for name, info in data.get("types", {}).items():
            if name.startswith("_") or name == "PLACEHOLDER_MORE_TYPES":
                continue
            self.types[name] = TypeInfo(
                name=name,
                vec_type=info["vec_type"],
                scalar_type=info["scalar_type"],
                field_name=info["field"],
                lanes=info["lanes"],
                width=info["width"],
                mask_type=info["mask"],
                ptr_type=info["ptr"],
                category=info["category"],
                decompose=info.get("decompose"),
            )

    def load_operations(self, path: Path):
        with open(path) as f:
            data = json.load(f)
        category = data.get("category", "")
        for op_def in data.get("operations", []):
            op = Operation(
                name=op_def["name"],
                signature=op_def["signature"],
                scalar_op=op_def.get("scalar_op", ""),
                doc=op_def.get("doc", ""),
                applies_to=op_def.get("applies_to", []),
                scalar_body=op_def.get("scalar_body"),
                scalar_vars=op_def.get("scalar_vars"),
                scalar_body_by_type=op_def.get("scalar_body_by_type"),
                scalar_vars_by_type=op_def.get("scalar_vars_by_type"),
                mask_type_by_type=op_def.get("mask_type_by_type"),
                name_pattern=op_def.get("name_pattern"),
                facade_name_pattern=op_def.get("facade_name_pattern"),
                scalar_name_pattern=op_def.get("scalar_name_pattern"),
                category=category,
            )
            self.operations.append(op)

    def build_slots(self):
        self.slots = []
        for op in self.operations:
            if op.signature in NO_TYPE_SIGNATURES and not op.applies_to:
                self.slots.append(SlotEntry(op=op, type_info=None))
                continue
            for type_name in op.applies_to:
                if type_name in self.types:
                    self.slots.append(SlotEntry(op=op, type_info=self.types[type_name]))

    def load_all(self):
        self.load_types(OPS_DIR / "types.json")
        for f in sorted(OPS_DIR.glob("*.json")):
            if f.name == "types.json":
                continue
            self.load_operations(f)
        self.build_slots()


# =============================================================================
# Code generators
# =============================================================================

def render_type_lines(value, type_info: Optional[TypeInfo]) -> list[str]:
    """Render optional JSON code templates for a specific vector type."""
    if value is None:
        return []
    if isinstance(value, list):
        raw_lines = value
    else:
        raw_lines = str(value).splitlines()
    rendered_lines = []
    for line in raw_lines:
        if type_info is not None:
            lane_bits = type_info.width // type_info.lanes if type_info.lanes > 0 else 0
            line = (
                line
                .replace("{field}", type_info.field_name)
                .replace("{type}", type_info.name)
                .replace("{scalar_type}", type_info.scalar_type)
                .replace("{lanes}", str(type_info.lanes))
                .replace("{lane_bits}", str(lane_bits))
            )
        else:
            line = (
                line
                .replace("{field}", "")
                .replace("{type}", "")
                .replace("{scalar_type}", "")
                .replace("{lanes}", "0")
                .replace("{lane_bits}", "0")
            )
        rendered_lines.append(line)
    return rendered_lines


def typed_template(mapping: Optional[dict], type_info: TypeInfo):
    """Return a per-type template from an operation definition, if present."""
    if not mapping:
        return None
    return mapping.get(type_info.name)


def code_uses_identifier(lines: list[str], identifier: str) -> bool:
    """Return true when rendered Pascal template lines reference an identifier."""
    pattern = re.compile(rf"\b{re.escape(identifier)}\b")
    return any(pattern.search(line) for line in lines)


def append_scalar_var_block(lines: list[str], scalar_vars: list[str], include_i: bool) -> None:
    """Append a Pascal var block, omitting unused generated loop indexes."""
    if not include_i and not scalar_vars:
        return
    if include_i and not scalar_vars:
        lines.append("var i: Integer;")
        return
    lines.append("var")
    if include_i:
        lines.append("  i: Integer;")
    for scalar_var in scalar_vars:
        lines.append(f"  {scalar_var.rstrip(';')};")


def select_mask_type(slot: SlotEntry) -> str:
    """Return the mask parameter type for Select-like slots."""
    mapping = slot.op.mask_type_by_type or {}
    return mapping.get(slot.type_info.name, slot.type_info.mask_type)


def pointer_ptr_len_result_type(signature: str) -> str:
    """Return the Pascal result type for pointer-pointer-length helper slots."""
    return POINTER_PTR_LEN_RESULT_TYPES[signature]


def pointer_len_result_type(signature: str) -> str:
    """Return the Pascal result type for pointer-length helper slots."""
    return POINTER_LEN_RESULT_TYPES[signature]


def pointer_len_byte_result_type(signature: str) -> str:
    """Return the Pascal result type for pointer-length-byte helper slots."""
    return POINTER_LEN_BYTE_RESULT_TYPES[signature]


def pointer_ptr_len_out_result_type(signature: str) -> str:
    """Return the Pascal result type for pointer-pointer-length helpers with out params."""
    return POINTER_PTR_LEN_OUT_RESULT_TYPES[signature]


def pointer_len_ptr_len_result_type(signature: str) -> str:
    """Return the Pascal result type for pointer-length/pointer-length helper slots."""
    return POINTER_LEN_PTR_LEN_RESULT_TYPES[signature]


def gen_signature(slot: SlotEntry) -> str:
    """Generate the function pointer type signature for a dispatch slot."""
    t = slot.type_info
    sig = slot.op.signature

    if sig == "binary":
        return f"function(const a, b: {t.vec_type}): {t.vec_type}"
    elif sig == "unary":
        return f"function(const a: {t.vec_type}): {t.vec_type}"
    elif sig == "compare":
        return f"function(const a, b: {t.vec_type}): {t.mask_type}"
    elif sig == "reduce":
        return f"function(const a: {t.vec_type}): {t.scalar_type}"
    elif sig == "reduce_binary":
        return f"function(const a, b: {t.vec_type}): {t.scalar_type}"
    elif sig == "load":
        return f"function(p: {t.ptr_type}): {t.vec_type}"
    elif sig == "store":
        return f"procedure(p: {t.ptr_type}; const a: {t.vec_type})"
    elif sig == "splat":
        return f"function(value: {t.scalar_type}): {t.vec_type}"
    elif sig == "zero":
        return f"function: {t.vec_type}"
    elif sig == "shift":
        return f"function(const a: {t.vec_type}; count: Integer): {t.vec_type}"
    elif sig == "ternary":
        return f"function(const a, b, c: {t.vec_type}): {t.vec_type}"
    elif sig == "select":
        return f"function(const mask: {select_mask_type(slot)}; const a, b: {t.vec_type}): {t.vec_type}"
    elif sig == "extract":
        return f"function(const a: {t.vec_type}; index: Integer): {t.scalar_type}"
    elif sig == "insert":
        return f"function(const a: {t.vec_type}; value: {t.scalar_type}; index: Integer): {t.vec_type}"
    elif sig == "mask_bool":
        return f"function(mask: {t.mask_type}): Boolean"
    elif sig == "mask_int":
        return f"function(mask: {t.mask_type}): Integer"
    elif sig in POINTER_LEN_RESULT_TYPES:
        return f"function(p: Pointer; len: SizeUInt): {pointer_len_result_type(sig)}"
    elif sig in POINTER_LEN_BYTE_RESULT_TYPES:
        return f"function(p: Pointer; len: SizeUInt; value: Byte): {pointer_len_byte_result_type(sig)}"
    elif sig in POINTER_PTR_LEN_RESULT_TYPES:
        return f"function(a, b: Pointer; len: SizeUInt): {pointer_ptr_len_result_type(sig)}"
    elif sig in POINTER_PTR_LEN_OUT_RESULT_TYPES:
        return f"function(a, b: Pointer; len: SizeUInt; out firstDiff, lastDiff: SizeUInt): {pointer_ptr_len_out_result_type(sig)}"
    elif sig in POINTER_LEN_PTR_LEN_RESULT_TYPES:
        return f"function(haystack: Pointer; haystackLen: SizeUInt; needle: Pointer; needleLen: SizeUInt): {pointer_len_ptr_len_result_type(sig)}"
    elif sig in POINTER_LEN_VOID_SIGNATURES:
        return "procedure(p: Pointer; len: SizeUInt)"
    elif sig in POINTER_LEN_BYTE_VOID_SIGNATURES:
        return "procedure(dst: Pointer; len: SizeUInt; value: Byte)"
    elif sig in POINTER_LEN_OUT_BYTE_VOID_SIGNATURES:
        return "procedure(p: Pointer; len: SizeUInt; out minVal, maxVal: Byte)"
    elif sig in POINTER_PTR_LEN_VOID_SIGNATURES:
        return "procedure(src, dst: Pointer; len: SizeUInt)"
    elif sig == "psingle_count_single":
        return "function(aSrc: PSingle; aCount: SizeUInt): Single"
    elif sig == "psingle_psingle_count_single":
        return "function(aSrc1, aSrc2: PSingle; aCount: SizeUInt): Single"
    elif sig == "psingle_psingle_psingle_count_void":
        return "procedure(aSrc1, aSrc2, aDst: PSingle; aCount: SizeUInt)"
    elif sig == "psingle_psingle_count_single_void":
        return "procedure(aSrc, aDst: PSingle; aCount: SizeUInt; aScalar: Single)"
    elif sig == "single_psingle_psingle_psingle_count_void":
        return "procedure(aAlpha: Single; aX, aY, aDst: PSingle; aCount: SizeUInt)"
    else:
        return f"{{unknown signature: {sig}}}"


def generate_dispatch_slots(registry: Registry) -> str:
    lines = [HEADER, "{ Dispatch table slots }", ""]
    current_category = ""
    for slot in registry.slots:
        if slot.op.category != current_category:
            current_category = slot.op.category
            lines.append(f"    {{ --- {current_category} --- }}")
        sig = gen_signature(slot)
        lines.append(f"    {slot.dispatch_field}: {sig};")
    return "\n".join(lines) + "\n"


def generate_scalar_decl(registry: Registry) -> str:
    lines = [HEADER, "{ Scalar implementation declarations }", ""]
    for slot in registry.slots:
        t = slot.type_info
        sig = slot.op.signature
        if sig == "binary":
            lines.append(
                f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.vec_type};"
            )
        elif sig == "unary":
            lines.append(
                f"function {slot.scalar_name}(const a: {t.vec_type}): {t.vec_type};"
            )
        elif sig == "compare":
            lines.append(
                f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.mask_type};"
            )
        elif sig == "reduce":
            lines.append(
                f"function {slot.scalar_name}(const a: {t.vec_type}): {t.scalar_type};"
            )
        elif sig == "shift":
            lines.append(
                f"function {slot.scalar_name}(const a: {t.vec_type}; count: Integer): {t.vec_type};"
            )
        elif sig == "load":
            lines.append(
                f"function {slot.scalar_name}(p: {t.ptr_type}): {t.vec_type};"
            )
        elif sig == "store":
            lines.append(
                f"procedure {slot.scalar_name}(p: {t.ptr_type}; const a: {t.vec_type});"
            )
        elif sig == "splat":
            lines.append(
                f"function {slot.scalar_name}(value: {t.scalar_type}): {t.vec_type};"
            )
        elif sig == "zero":
            lines.append(
                f"function {slot.scalar_name}: {t.vec_type};"
            )
        elif sig == "ternary":
            lines.append(
                f"function {slot.scalar_name}(const a, b, c: {t.vec_type}): {t.vec_type};"
            )
        elif sig == "select":
            lines.append(
                f"function {slot.scalar_name}(const mask: {select_mask_type(slot)}; const a, b: {t.vec_type}): {t.vec_type};"
            )
        elif sig == "extract":
            lines.append(
                f"function {slot.scalar_name}(const a: {t.vec_type}; index: Integer): {t.scalar_type};"
            )
        elif sig == "insert":
            lines.append(
                f"function {slot.scalar_name}(const a: {t.vec_type}; value: {t.scalar_type}; index: Integer): {t.vec_type};"
            )
        elif sig == "reduce_binary":
            lines.append(
                f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.scalar_type};"
            )
        elif sig == "mask_bool":
            lines.append(
                f"function {slot.scalar_name}(mask: {t.mask_type}): Boolean;"
            )
        elif sig == "mask_int":
            lines.append(
                f"function {slot.scalar_name}(mask: {t.mask_type}): Integer;"
            )
        elif sig in POINTER_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(p: Pointer; len: SizeUInt): {pointer_len_result_type(sig)};"
            )
        elif sig in POINTER_LEN_BYTE_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(p: Pointer; len: SizeUInt; value: Byte): {pointer_len_byte_result_type(sig)};"
            )
        elif sig in POINTER_PTR_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(a, b: Pointer; len: SizeUInt): {pointer_ptr_len_result_type(sig)};"
            )
        elif sig in POINTER_PTR_LEN_OUT_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(a, b: Pointer; len: SizeUInt; out firstDiff, lastDiff: SizeUInt): {pointer_ptr_len_out_result_type(sig)};"
            )
        elif sig in POINTER_LEN_PTR_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(haystack: Pointer; haystackLen: SizeUInt; needle: Pointer; needleLen: SizeUInt): {pointer_len_ptr_len_result_type(sig)};"
            )
        elif sig in POINTER_LEN_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.scalar_name}(p: Pointer; len: SizeUInt);"
            )
        elif sig in POINTER_LEN_BYTE_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.scalar_name}(dst: Pointer; len: SizeUInt; value: Byte);"
            )
        elif sig in POINTER_LEN_OUT_BYTE_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.scalar_name}(p: Pointer; len: SizeUInt; out minVal, maxVal: Byte);"
            )
        elif sig in POINTER_PTR_LEN_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.scalar_name}(src, dst: Pointer; len: SizeUInt);"
            )
        elif sig == "psingle_count_single":
            lines.append(
                f"function {slot.scalar_name}(aSrc: PSingle; aCount: SizeUInt): Single;"
            )
        elif sig == "psingle_psingle_count_single":
            lines.append(
                f"function {slot.scalar_name}(aSrc1, aSrc2: PSingle; aCount: SizeUInt): Single;"
            )
        elif sig == "psingle_psingle_psingle_count_void":
            lines.append(
                f"procedure {slot.scalar_name}(aSrc1, aSrc2, aDst: PSingle; aCount: SizeUInt);"
            )
        elif sig == "psingle_psingle_count_single_void":
            lines.append(
                f"procedure {slot.scalar_name}(aSrc, aDst: PSingle; aCount: SizeUInt; aScalar: Single);"
            )
        elif sig == "single_psingle_psingle_psingle_count_void":
            lines.append(
                f"procedure {slot.scalar_name}(aAlpha: Single; aX, aY, aDst: PSingle; aCount: SizeUInt);"
            )
    return "\n".join(lines) + "\n"


def generate_scalar_impl(registry: Registry) -> str:
    lines = [HEADER, "{ Scalar implementation bodies }", "", "{$PUSH}{$Q-}{$R-}", ""]
    for slot in registry.slots:
        t = slot.type_info
        sig = slot.op.signature
        op = slot.op

        if sig == "binary":
            lines.append(f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.vec_type};")
            type_lines = render_type_lines(typed_template(op.scalar_body_by_type, t), t)
            scalar_vars = render_type_lines(typed_template(op.scalar_vars_by_type, t), t)
            append_scalar_var_block(lines, scalar_vars, include_i=not type_lines or code_uses_identifier(type_lines, "i"))
            lines.append("begin")
            if type_lines:
                for body_line in type_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            elif op.scalar_body:
                body = op.scalar_body.replace("{field}", t.field_name)
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    {body};")
            elif op.scalar_op in ("+", "-", "*", "/", "and", "or", "xor"):
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(
                    f"    Result.{t.field_name}[i] := a.{t.field_name}[i] "
                    f"{op.scalar_op} b.{t.field_name}[i];"
                )
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := a;")
            lines.append("end;")
            lines.append("")

        elif sig == "unary":
            lines.append(f"function {slot.scalar_name}(const a: {t.vec_type}): {t.vec_type};")
            type_lines = render_type_lines(typed_template(op.scalar_body_by_type, t), t)
            scalar_vars = render_type_lines(typed_template(op.scalar_vars_by_type, t), t)
            append_scalar_var_block(lines, scalar_vars, include_i=not type_lines or code_uses_identifier(type_lines, "i"))
            lines.append("begin")
            if type_lines:
                for body_line in type_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            elif op.scalar_body:
                body = op.scalar_body.replace("{field}", t.field_name)
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    {body};")
            elif op.scalar_op == "not":
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    Result.{t.field_name}[i] := not a.{t.field_name}[i];")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := a;")
            lines.append("end;")
            lines.append("")

        elif sig == "shift":
            lines.append(f"function {slot.scalar_name}(const a: {t.vec_type}; count: Integer): {t.vec_type};")
            type_lines = render_type_lines(typed_template(op.scalar_body_by_type, t), t)
            scalar_vars = render_type_lines(typed_template(op.scalar_vars_by_type, t), t)
            # If scalar_body is a list, treat it as multi-line body (like type_lines)
            fallback_lines: list[str] = []
            if not type_lines and op.scalar_body and isinstance(op.scalar_body, list):
                fallback_lines = render_type_lines(op.scalar_body, t)
            append_scalar_var_block(lines, scalar_vars, include_i=not (type_lines or fallback_lines) or
                code_uses_identifier(type_lines or fallback_lines, "i"))
            lines.append("begin")
            if type_lines:
                for body_line in type_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            elif fallback_lines:
                for body_line in fallback_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            elif op.scalar_body and isinstance(op.scalar_body, str):
                body = op.scalar_body.replace("{field}", t.field_name)
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    {body};")
            elif op.scalar_op in ("shl", "shr"):
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    Result.{t.field_name}[i] := a.{t.field_name}[i] {op.scalar_op} count;")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := a;")
            lines.append("end;")
            lines.append("")

        elif sig == "compare":
            lines.append(f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.mask_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            lines.append(f"  Result := 0;")
            lines.append(f"  for i := 0 to {t.lanes - 1} do")
            lines.append(f"    if a.{t.field_name}[i] {op.scalar_op} b.{t.field_name}[i] then")
            lines.append(f"      Result := Result or ({t.mask_type}(1) shl i);")
            lines.append("end;")
            lines.append("")

        elif sig == "reduce":
            lines.append(f"function {slot.scalar_name}(const a: {t.vec_type}): {t.scalar_type};")
            type_lines = render_type_lines(typed_template(op.scalar_body_by_type, t), t)
            scalar_vars = render_type_lines(typed_template(op.scalar_vars_by_type, t), t)
            append_scalar_var_block(lines, scalar_vars, include_i=not type_lines or code_uses_identifier(type_lines, "i"))
            lines.append("begin")
            if type_lines:
                for body_line in type_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            elif "Add" in op.name:
                lines.append(f"  Result := a.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    Result := Result + a.{t.field_name}[i];")
            elif "Min" in op.name:
                lines.append(f"  Result := a.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    if a.{t.field_name}[i] < Result then Result := a.{t.field_name}[i];")
            elif "Max" in op.name:
                lines.append(f"  Result := a.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    if a.{t.field_name}[i] > Result then Result := a.{t.field_name}[i];")
            elif "Mul" in op.name:
                lines.append(f"  Result := a.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    Result := Result * a.{t.field_name}[i];")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := 0;")
            lines.append("end;")
            lines.append("")

        elif sig == "load":
            lines.append(f"function {slot.scalar_name}(p: {t.ptr_type}): {t.vec_type};")
            if op.scalar_op == "custom":
                body_lines = render_type_lines(typed_template(op.scalar_body_by_type, t), t)
                if not body_lines:
                    body_lines = render_type_lines(op.scalar_body, None)
                if not body_lines:
                    raise ValueError(f"Custom load op {slot.dispatch_field} missing scalar body")
                scalar_vars = render_type_lines(typed_template(op.scalar_vars_by_type, t), t)
                append_scalar_var_block(lines, scalar_vars, include_i=code_uses_identifier(body_lines, "i"))
                lines.append("begin")
                for body_line in body_lines:
                    lines.append(f"  {body_line}" if body_line else "")
                lines.append("end;")
            else:
                lines.append("var i: Integer;")
                lines.append("begin")
                lines.append(f"  Assert(p <> nil, '{slot.scalar_name}: pointer is nil');")
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    Result.{t.field_name}[i] := p[i];")
                lines.append("end;")
            lines.append("")

        elif sig == "store":
            lines.append(f"procedure {slot.scalar_name}(p: {t.ptr_type}; const a: {t.vec_type});")
            if op.scalar_op == "custom":
                body_lines = render_type_lines(typed_template(op.scalar_body_by_type, t), t)
                if not body_lines:
                    body_lines = render_type_lines(op.scalar_body, None)
                if not body_lines:
                    raise ValueError(f"Custom store op {slot.dispatch_field} missing scalar body")
                scalar_vars = render_type_lines(typed_template(op.scalar_vars_by_type, t), t)
                append_scalar_var_block(lines, scalar_vars, include_i=code_uses_identifier(body_lines, "i"))
                lines.append("begin")
                for body_line in body_lines:
                    lines.append(f"  {body_line}" if body_line else "")
                lines.append("end;")
            else:
                lines.append("var i: Integer;")
                lines.append("begin")
                lines.append(f"  Assert(p <> nil, '{slot.scalar_name}: pointer is nil');")
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    p[i] := a.{t.field_name}[i];")
                lines.append("end;")
            lines.append("")

        elif sig == "splat":
            lines.append(f"function {slot.scalar_name}(value: {t.scalar_type}): {t.vec_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            lines.append(f"  for i := 0 to {t.lanes - 1} do")
            lines.append(f"    Result.{t.field_name}[i] := value;")
            lines.append("end;")
            lines.append("")

        elif sig == "zero":
            lines.append(f"function {slot.scalar_name}: {t.vec_type};")
            lines.append("begin")
            lines.append(f"  FillChar(Result, SizeOf(Result), 0);")
            lines.append("end;")
            lines.append("")

        elif sig == "ternary":
            lines.append(f"function {slot.scalar_name}(const a, b, c: {t.vec_type}): {t.vec_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            if op.scalar_body:
                body = op.scalar_body.replace("{field}", t.field_name)
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    {body};")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := a;")
            lines.append("end;")
            lines.append("")

        elif sig == "select":
            lines.append(f"function {slot.scalar_name}(const mask: {select_mask_type(slot)}; const a, b: {t.vec_type}): {t.vec_type};")
            type_lines = render_type_lines(typed_template(op.scalar_body_by_type, t), t)
            scalar_vars = render_type_lines(typed_template(op.scalar_vars_by_type, t), t)
            append_scalar_var_block(lines, scalar_vars, include_i=not type_lines or code_uses_identifier(type_lines, "i"))
            lines.append("begin")
            if type_lines:
                for body_line in type_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            elif op.scalar_body:
                body = op.scalar_body.replace("{field}", t.field_name)
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    {body};")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := a;")
            lines.append("end;")
            lines.append("")

        elif sig == "extract":
            lines.append(f"function {slot.scalar_name}(const a: {t.vec_type}; index: Integer): {t.scalar_type};")
            lines.append("var LIndex: Integer;")
            lines.append("begin")
            lines.append("  LIndex := index;")
            lines.append("  if LIndex < 0 then LIndex := 0")
            lines.append(f"  else if LIndex > {t.lanes - 1} then LIndex := {t.lanes - 1};")
            lines.append(f"  Result := a.{t.field_name}[LIndex];")
            lines.append("end;")
            lines.append("")

        elif sig == "insert":
            lines.append(f"function {slot.scalar_name}(const a: {t.vec_type}; value: {t.scalar_type}; index: Integer): {t.vec_type};")
            lines.append("var LIndex: Integer;")
            lines.append("begin")
            lines.append("  LIndex := index;")
            lines.append("  if LIndex < 0 then LIndex := 0")
            lines.append(f"  else if LIndex > {t.lanes - 1} then LIndex := {t.lanes - 1};")
            lines.append("  Result := a;")
            lines.append(f"  Result.{t.field_name}[LIndex] := value;")
            lines.append("end;")
            lines.append("")

        elif sig == "reduce_binary":
            lines.append(f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.scalar_type};")
            type_lines = render_type_lines(typed_template(op.scalar_body_by_type, t), t)
            scalar_vars = render_type_lines(typed_template(op.scalar_vars_by_type, t), t)
            append_scalar_var_block(lines, scalar_vars, include_i=not type_lines or code_uses_identifier(type_lines, "i"))
            lines.append("begin")
            if type_lines:
                for body_line in type_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            else:
                lines.append(f"  Result := a.{t.field_name}[0] * b.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    Result := Result + a.{t.field_name}[i] * b.{t.field_name}[i];")
            lines.append("end;")
            lines.append("")

        elif sig == "mask_bool":
            lines.append(f"function {slot.scalar_name}(mask: {t.mask_type}): Boolean;")
            lines.append("begin")
            if op.scalar_body:
                body = op.scalar_body.replace("{mask_all}", t.name.upper() + "_ALL_SET")
                lines.append(f"  {body};")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append("  Result := False;")
            lines.append("end;")
            lines.append("")

        elif sig == "mask_int":
            lines.append(f"function {slot.scalar_name}(mask: {t.mask_type}): Integer;")
            lines.append("var i: Integer;")
            lines.append("begin")
            if op.name == "PopCount":
                lines.append("  Result := 0;")
                lines.append(f"  mask := mask and {t.name.upper()}_ALL_SET;")
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append("    if (mask and (1 shl i)) <> 0 then")
                lines.append("      Inc(Result);")
            elif op.name == "FirstSet":
                lines.append(f"  mask := mask and {t.name.upper()}_ALL_SET;")
                lines.append("  if mask = 0 then")
                lines.append("    Exit(-1);")
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append("    if (mask and (1 shl i)) <> 0 then")
                lines.append("      Exit(i);")
                lines.append("  Result := -1;")
            elif op.scalar_body:
                body = op.scalar_body.replace("{mask_all}", t.name.upper() + "_ALL_SET")
                lines.append(f"  {body};")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append("  Result := 0;")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(p: Pointer; len: SizeUInt): {pointer_len_result_type(sig)};"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            if body_lines:
                for body_line in body_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            else:
                lines.append("  Result := False;")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_LEN_BYTE_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(p: Pointer; len: SizeUInt; value: Byte): {pointer_len_byte_result_type(sig)};"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            if body_lines:
                for body_line in body_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            else:
                lines.append("  Result := 0;")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_PTR_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(a, b: Pointer; len: SizeUInt): {pointer_ptr_len_result_type(sig)};"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            if body_lines:
                for body_line in body_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            else:
                lines.append("  Result := False;")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_PTR_LEN_OUT_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(a, b: Pointer; len: SizeUInt; out firstDiff, lastDiff: SizeUInt): {pointer_ptr_len_out_result_type(sig)};"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_LEN_PTR_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.scalar_name}(haystack: Pointer; haystackLen: SizeUInt; needle: Pointer; needleLen: SizeUInt): {pointer_len_ptr_len_result_type(sig)};"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_LEN_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.scalar_name}(p: Pointer; len: SizeUInt);"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=code_uses_identifier(body_lines, "i"))
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_LEN_BYTE_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.scalar_name}(dst: Pointer; len: SizeUInt; value: Byte);"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=code_uses_identifier(body_lines, "i"))
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_LEN_OUT_BYTE_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.scalar_name}(p: Pointer; len: SizeUInt; out minVal, maxVal: Byte);"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

        elif sig in POINTER_PTR_LEN_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.scalar_name}(src, dst: Pointer; len: SizeUInt);"
            )
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=code_uses_identifier(body_lines, "i"))
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

        elif sig == "psingle_count_single":
            lines.append(f"function {slot.scalar_name}(aSrc: PSingle; aCount: SizeUInt): Single;")
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            if body_lines:
                for body_line in body_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            else:
                lines.append("  Result := 0;")
            lines.append("end;")
            lines.append("")

        elif sig == "psingle_psingle_count_single":
            lines.append(f"function {slot.scalar_name}(aSrc1, aSrc2: PSingle; aCount: SizeUInt): Single;")
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            if body_lines:
                for body_line in body_lines:
                    lines.append(f"  {body_line}" if body_line else "")
            else:
                lines.append("  Result := 0;")
            lines.append("end;")
            lines.append("")

        elif sig == "psingle_psingle_psingle_count_void":
            lines.append(f"procedure {slot.scalar_name}(aSrc1, aSrc2, aDst: PSingle; aCount: SizeUInt);")
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

        elif sig == "psingle_psingle_count_single_void":
            lines.append(f"procedure {slot.scalar_name}(aSrc, aDst: PSingle; aCount: SizeUInt; aScalar: Single);")
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

        elif sig == "single_psingle_psingle_psingle_count_void":
            lines.append(f"procedure {slot.scalar_name}(aAlpha: Single; aX, aY, aDst: PSingle; aCount: SizeUInt);")
            scalar_vars = render_type_lines(op.scalar_vars, None)
            body_lines = render_type_lines(op.scalar_body, None)
            append_scalar_var_block(lines, scalar_vars, include_i=False)
            lines.append("begin")
            for body_line in body_lines:
                lines.append(f"  {body_line}" if body_line else "")
            lines.append("end;")
            lines.append("")

    lines.append("{$POP}")
    return "\n".join(lines) + "\n"


def generate_fillbase(registry: Registry) -> str:
    lines = [HEADER, "{ FillBaseDispatchTable assignments }", ""]
    for slot in registry.slots:
        lines.append(f"  aTable.{slot.dispatch_field} := @{slot.scalar_name};")
    return "\n".join(lines) + "\n"


def generate_facade_decl(registry: Registry) -> str:
    lines = [HEADER, "{ Public facade function declarations }", ""]
    for slot in registry.slots:
        t = slot.type_info
        sig = slot.op.signature
        doc = slot.op.doc
        if doc:
            if t is None:
                lines.append(f"{{ {doc} }}")
            else:
                lines.append(f"{{ {doc}: {t.name} }}")
        if sig == "binary":
            lines.append(
                f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.vec_type}; inline;"
            )
        elif sig == "unary":
            lines.append(
                f"function {slot.facade_name}(const a: {t.vec_type}): {t.vec_type}; inline;"
            )
        elif sig == "compare":
            lines.append(
                f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.mask_type}; inline;"
            )
        elif sig == "reduce":
            lines.append(
                f"function {slot.facade_name}(const a: {t.vec_type}): {t.scalar_type}; inline;"
            )
        elif sig == "shift":
            lines.append(
                f"function {slot.facade_name}(const a: {t.vec_type}; count: Integer): {t.vec_type}; inline;"
            )
        elif sig == "load":
            lines.append(
                f"function {slot.facade_name}(p: {t.ptr_type}): {t.vec_type}; inline;"
            )
        elif sig == "store":
            lines.append(
                f"procedure {slot.facade_name}(p: {t.ptr_type}; const a: {t.vec_type}); inline;"
            )
        elif sig == "splat":
            lines.append(
                f"function {slot.facade_name}(value: {t.scalar_type}): {t.vec_type}; inline;"
            )
        elif sig == "zero":
            lines.append(
                f"function {slot.facade_name}: {t.vec_type}; inline;"
            )
        elif sig == "ternary":
            lines.append(
                f"function {slot.facade_name}(const a, b, c: {t.vec_type}): {t.vec_type}; inline;"
            )
        elif sig == "select":
            lines.append(
                f"function {slot.facade_name}(const mask: {select_mask_type(slot)}; const a, b: {t.vec_type}): {t.vec_type}; inline;"
            )
        elif sig == "extract":
            lines.append(
                f"function {slot.facade_name}(const a: {t.vec_type}; index: Integer): {t.scalar_type}; inline;"
            )
        elif sig == "insert":
            lines.append(
                f"function {slot.facade_name}(const a: {t.vec_type}; value: {t.scalar_type}; index: Integer): {t.vec_type}; inline;"
            )
        elif sig == "reduce_binary":
            lines.append(
                f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.scalar_type}; inline;"
            )
        elif sig == "mask_bool":
            lines.append(
                f"function {slot.facade_name}(mask: {t.mask_type}): Boolean; inline;"
            )
        elif sig == "mask_int":
            lines.append(
                f"function {slot.facade_name}(mask: {t.mask_type}): Integer; inline;"
            )
        elif sig in POINTER_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(p: Pointer; len: SizeUInt): {pointer_len_result_type(sig)}; inline;"
            )
        elif sig in POINTER_LEN_BYTE_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(p: Pointer; len: SizeUInt; value: Byte): {pointer_len_byte_result_type(sig)}; inline;"
            )
        elif sig in POINTER_PTR_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(a, b: Pointer; len: SizeUInt): {pointer_ptr_len_result_type(sig)}; inline;"
            )
        elif sig in POINTER_PTR_LEN_OUT_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(a, b: Pointer; len: SizeUInt; out firstDiff, lastDiff: SizeUInt): {pointer_ptr_len_out_result_type(sig)}; inline;"
            )
        elif sig in POINTER_LEN_PTR_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(haystack: Pointer; haystackLen: SizeUInt; needle: Pointer; needleLen: SizeUInt): {pointer_len_ptr_len_result_type(sig)}; inline;"
            )
        elif sig in POINTER_LEN_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.facade_name}(p: Pointer; len: SizeUInt); inline;"
            )
        elif sig in POINTER_LEN_BYTE_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.facade_name}(dst: Pointer; len: SizeUInt; value: Byte); inline;"
            )
        elif sig in POINTER_LEN_OUT_BYTE_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.facade_name}(p: Pointer; len: SizeUInt; out minVal, maxVal: Byte); inline;"
            )
        elif sig in POINTER_PTR_LEN_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.facade_name}(src, dst: Pointer; len: SizeUInt); inline;"
            )
        elif sig == "psingle_count_single":
            lines.append(
                f"function {slot.facade_name}(aSrc: PSingle; aCount: SizeUInt): Single; inline;"
            )
        elif sig == "psingle_psingle_count_single":
            lines.append(
                f"function {slot.facade_name}(aSrc1, aSrc2: PSingle; aCount: SizeUInt): Single; inline;"
            )
        elif sig == "psingle_psingle_psingle_count_void":
            lines.append(
                f"procedure {slot.facade_name}(aSrc1, aSrc2, aDst: PSingle; aCount: SizeUInt); inline;"
            )
        elif sig == "psingle_psingle_count_single_void":
            lines.append(
                f"procedure {slot.facade_name}(aSrc, aDst: PSingle; aCount: SizeUInt; aScalar: Single); inline;"
            )
        elif sig == "single_psingle_psingle_psingle_count_void":
            lines.append(
                f"procedure {slot.facade_name}(aAlpha: Single; aX, aY, aDst: PSingle; aCount: SizeUInt); inline;"
            )
    return "\n".join(lines) + "\n"


def generate_facade_impl(registry: Registry) -> str:
    lines = [HEADER, "{ Public facade function implementations }", ""]
    for slot in registry.slots:
        t = slot.type_info
        sig = slot.op.signature

        if sig == "binary":
            lines.append(f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, b);")
            lines.append("end;")
            lines.append("")
        elif sig == "unary":
            lines.append(f"function {slot.facade_name}(const a: {t.vec_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a);")
            lines.append("end;")
            lines.append("")
        elif sig == "compare":
            lines.append(f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.mask_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, b);")
            lines.append("end;")
            lines.append("")
        elif sig == "reduce":
            lines.append(f"function {slot.facade_name}(const a: {t.vec_type}): {t.scalar_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a);")
            lines.append("end;")
            lines.append("")
        elif sig == "shift":
            lines.append(f"function {slot.facade_name}(const a: {t.vec_type}; count: Integer): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, count);")
            lines.append("end;")
            lines.append("")
        elif sig == "load":
            lines.append(f"function {slot.facade_name}(p: {t.ptr_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(p);")
            lines.append("end;")
            lines.append("")
        elif sig == "store":
            lines.append(f"procedure {slot.facade_name}(p: {t.ptr_type}; const a: {t.vec_type});")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(p, a);")
            lines.append("end;")
            lines.append("")
        elif sig == "splat":
            lines.append(f"function {slot.facade_name}(value: {t.scalar_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(value);")
            lines.append("end;")
            lines.append("")
        elif sig == "zero":
            lines.append(f"function {slot.facade_name}: {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field};")
            lines.append("end;")
            lines.append("")
        elif sig == "ternary":
            lines.append(f"function {slot.facade_name}(const a, b, c: {t.vec_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, b, c);")
            lines.append("end;")
            lines.append("")
        elif sig == "select":
            lines.append(f"function {slot.facade_name}(const mask: {select_mask_type(slot)}; const a, b: {t.vec_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(mask, a, b);")
            lines.append("end;")
            lines.append("")
        elif sig == "reduce_binary":
            lines.append(f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.scalar_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, b);")
            lines.append("end;")
            lines.append("")
        elif sig == "mask_bool":
            lines.append(f"function {slot.facade_name}(mask: {t.mask_type}): Boolean;")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(mask);")
            lines.append("end;")
            lines.append("")
        elif sig == "mask_int":
            lines.append(f"function {slot.facade_name}(mask: {t.mask_type}): Integer;")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(mask);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(p: Pointer; len: SizeUInt): {pointer_len_result_type(sig)};"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(p, len);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_LEN_BYTE_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(p: Pointer; len: SizeUInt; value: Byte): {pointer_len_byte_result_type(sig)};"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(p, len, value);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_PTR_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(a, b: Pointer; len: SizeUInt): {pointer_ptr_len_result_type(sig)};"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, b, len);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_PTR_LEN_OUT_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(a, b: Pointer; len: SizeUInt; out firstDiff, lastDiff: SizeUInt): {pointer_ptr_len_out_result_type(sig)};"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, b, len, firstDiff, lastDiff);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_LEN_PTR_LEN_RESULT_TYPES:
            lines.append(
                f"function {slot.facade_name}(haystack: Pointer; haystackLen: SizeUInt; needle: Pointer; needleLen: SizeUInt): {pointer_len_ptr_len_result_type(sig)};"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(haystack, haystackLen, needle, needleLen);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_LEN_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.facade_name}(p: Pointer; len: SizeUInt);"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(p, len);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_LEN_BYTE_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.facade_name}(dst: Pointer; len: SizeUInt; value: Byte);"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(dst, len, value);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_LEN_OUT_BYTE_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.facade_name}(p: Pointer; len: SizeUInt; out minVal, maxVal: Byte);"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(p, len, minVal, maxVal);")
            lines.append("end;")
            lines.append("")
        elif sig in POINTER_PTR_LEN_VOID_SIGNATURES:
            lines.append(
                f"procedure {slot.facade_name}(src, dst: Pointer; len: SizeUInt);"
            )
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(src, dst, len);")
            lines.append("end;")
            lines.append("")
        elif sig == "psingle_count_single":
            lines.append(f"function {slot.facade_name}(aSrc: PSingle; aCount: SizeUInt): Single;")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(aSrc, aCount);")
            lines.append("end;")
            lines.append("")
        elif sig == "psingle_psingle_count_single":
            lines.append(f"function {slot.facade_name}(aSrc1, aSrc2: PSingle; aCount: SizeUInt): Single;")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(aSrc1, aSrc2, aCount);")
            lines.append("end;")
            lines.append("")

        elif sig == "psingle_psingle_psingle_count_void":
            lines.append(f"procedure {slot.facade_name}(aSrc1, aSrc2, aDst: PSingle; aCount: SizeUInt);")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(aSrc1, aSrc2, aDst, aCount);")
            lines.append("end;")
            lines.append("")

        elif sig == "psingle_psingle_count_single_void":
            lines.append(f"procedure {slot.facade_name}(aSrc, aDst: PSingle; aCount: SizeUInt; aScalar: Single);")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(aSrc, aDst, aCount, aScalar);")
            lines.append("end;")
            lines.append("")

        elif sig == "single_psingle_psingle_psingle_count_void":
            lines.append(f"procedure {slot.facade_name}(aAlpha: Single; aX, aY, aDst: PSingle; aCount: SizeUInt);")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(aAlpha, aX, aY, aDst, aCount);")
            lines.append("end;")
            lines.append("")

    return "\n".join(lines) + "\n"


# =============================================================================
# Audit: parse existing dispatch table and compare
# =============================================================================

import re

def parse_existing_dispatch_table(dispatch_path: Path) -> dict[str, str]:
    """Parse existing TSimdDispatchTable fields from dispatch.pas.
    Returns dict of {field_name: full_signature_line}"""
    slots = {}
    pattern = re.compile(r'^\s+(\w+):\s+(function|procedure)\s*(.+);', re.IGNORECASE)
    with open(dispatch_path) as f:
        in_record = False
        for line in f:
            if 'TSimdDispatchTable = record' in line:
                in_record = True
                continue
            if in_record and line.strip().startswith('end;'):
                break
            if in_record:
                m = pattern.match(line)
                if m:
                    field_name = m.group(1)
                    sig_type = m.group(2).lower()
                    sig_rest = m.group(3).strip()
                    slots[field_name] = f"{sig_type}{sig_rest}"
    return slots


def run_audit(registry: Registry):
    """Compare generated slots against existing dispatch table."""
    dispatch_path = PROJECT_ROOT / "src" / "nextpas.core.simd.dispatch.pas"
    if not dispatch_path.exists():
        print("[AUDIT] ERROR: dispatch.pas not found")
        return

    existing = parse_existing_dispatch_table(dispatch_path)
    generated = {}
    for slot in registry.slots:
        sig = gen_signature(slot)
        generated[slot.dispatch_field] = sig

    existing_names = set(existing.keys())
    generated_names = set(generated.keys())

    matched = existing_names & generated_names
    missing_from_gen = existing_names - generated_names
    extra_in_gen = generated_names - existing_names

    # Check signature compatibility for matched slots
    sig_matches = []
    sig_mismatches = []
    for name in sorted(matched):
        existing_sig = existing[name].rstrip(';').strip()
        gen_sig = generated[name].rstrip(';').strip()
        # Normalize: remove parameter names, keep only types
        def normalize_sig(s):
            s = re.sub(r'\s+', ' ', s.lower())
            # Remove parameter names: "const a, b: type" -> "const type, type".
            # Preserve by-reference modifiers so out/var signatures stay distinct.
            # For function pointer compatibility, only types matter
            s = re.sub(r'\b((?:const|out|var)\s+)?\w+(?:,\s*\w+)*:\s*', r'\1', s)
            return s
        e_norm = normalize_sig(existing_sig)
        g_norm = normalize_sig(gen_sig)
        if e_norm == g_norm:
            sig_matches.append(name)
        else:
            sig_mismatches.append((name, existing[name], generated[name]))

    # Print report
    print(f"\n{'='*70}")
    print(f"  SIMD DISPATCH TABLE AUDIT REPORT")
    print(f"{'='*70}")
    print(f"\n  Existing slots:  {len(existing_names)}")
    print(f"  Generated slots: {len(generated_names)}")
    print(f"  Matched:         {len(matched)} ({len(sig_matches)} compatible, {len(sig_mismatches)} mismatched)")
    print(f"  Missing (not in simdgen): {len(missing_from_gen)}")
    print(f"  Extra (in simdgen only):  {len(extra_in_gen)}")

    coverage_pct = len(matched) / len(existing_names) * 100 if existing_names else 0
    print(f"\n  Coverage: {coverage_pct:.1f}%")

    if sig_mismatches:
        print(f"\n  --- SIGNATURE MISMATCHES ({len(sig_mismatches)}) ---")
        for name, e_sig, g_sig in sig_mismatches[:20]:
            print(f"    {name}:")
            print(f"      existing:  {e_sig}")
            print(f"      generated: {g_sig}")

    if missing_from_gen:
        # Categorize missing slots
        categories: dict[str, list[str]] = {}
        for name in sorted(missing_from_gen):
            # Try to extract operation prefix
            op = re.sub(r'(F32x4|F32x8|F32x16|F64x2|F64x4|F64x8|I32x4|I32x8|I32x16|'
                       r'I64x2|I64x4|I64x8|U32x4|U32x8|U32x16|U64x2|U64x4|U64x8|'
                       r'I16x8|I16x32|I8x16|I8x64|U16x8|U8x16|U8x64|'
                       r'Mask2|Mask4|Mask8|Mask16|F32x3)$', '', name)
            if not op:
                op = name
            categories.setdefault(op, []).append(name)

        print(f"\n  --- MISSING FROM SIMDGEN ({len(missing_from_gen)}) ---")
        print(f"  (grouped by operation)")
        for op in sorted(categories.keys()):
            slots_list = categories[op]
            types_str = ', '.join(s.replace(op, '') for s in slots_list[:8])
            suffix = f" +{len(slots_list)-8} more" if len(slots_list) > 8 else ""
            print(f"    {op}: [{types_str}{suffix}]")

    if extra_in_gen:
        print(f"\n  --- EXTRA IN SIMDGEN (not in existing) ({len(extra_in_gen)}) ---")
        for name in sorted(extra_in_gen)[:20]:
            print(f"    {name}")

    print(f"\n{'='*70}")

    # Summary line for CI
    status = "OK" if not sig_mismatches and not extra_in_gen else "DRIFT"
    print(f"SIMDGEN_AUDIT existing={len(existing_names)} generated={len(generated_names)} "
          f"matched={len(matched)} compatible={len(sig_matches)} "
          f"mismatched={len(sig_mismatches)} missing={len(missing_from_gen)} "
          f"extra={len(extra_in_gen)} coverage={coverage_pct:.1f}% status={status}")


# =============================================================================
# Main
# =============================================================================

def canonical_sort_key(slot: SlotEntry) -> tuple[int, str, str]:
    """Keep generated include files stable and reviewable by vector family."""
    if slot.type_info is None:
        return (9999, slot.op.category, slot.base_name)
    return (slot.type_info.width, slot.type_info.name, slot.op.category)


def main() -> int:
    verify_mode = "--verify" in sys.argv
    dry_run = "--dry-run" in sys.argv
    # Current checked-in generated files use type-order. Keep --sort-by-type as
    # a compatibility spelling, but make the canonical default non-surprising.
    sort_by_type = True
    audit_mode = "--audit" in sys.argv
    category_filter = None
    for arg in sys.argv:
        if arg.startswith("--category="):
            category_filter = arg.split("=", 1)[1]

    registry = Registry()
    registry.load_all()

    if category_filter:
        registry.slots = [s for s in registry.slots if s.op.category == category_filter]

    if sort_by_type:
        registry.slots.sort(key=canonical_sort_key)

    print(f"[simdgen] Loaded {len(registry.types)} types, "
          f"{len(registry.operations)} operations, "
          f"{len(registry.slots)} slots")

    if audit_mode:
        run_audit(registry)
        return 0

    generators = {
        "nextpas.core.simd.dispatch.slots.inc": generate_dispatch_slots,
        "nextpas.core.simd.scalar.decl.inc": generate_scalar_decl,
        "nextpas.core.simd.scalar.impl.inc": generate_scalar_impl,
        "nextpas.core.simd.fillbase.inc": generate_fillbase,
        "nextpas.core.simd.facade.decl.inc": generate_facade_decl,
        "nextpas.core.simd.facade.impl.inc": generate_facade_impl,
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    verify_failures = 0
    for filename, gen_func in generators.items():
        content = gen_func(registry)
        output_path = OUTPUT_DIR / filename

        if dry_run:
            print(f"\n{'='*60}")
            print(f"  {filename} ({len(content.splitlines())} lines)")
            print(f"{'='*60}")
            print(content[:2000])
            if len(content) > 2000:
                print(f"  ... ({len(content)} chars total)")
            continue

        if verify_mode:
            if output_path.exists():
                existing = output_path.read_text()
                if existing == content:
                    print(f"  [OK] {filename}")
                else:
                    print(f"  [DRIFT] {filename} - generated differs from existing")
                    verify_failures += 1
            else:
                print(f"  [NEW] {filename} - does not exist yet")
                verify_failures += 1
            continue

        output_path.write_text(content)
        print(f"  [WRITE] {filename} ({len(content.splitlines())} lines)")

    if verify_mode:
        # Also verify AVX2 batch kernels
        from simdgen_batch import verify_avx2_batch
        print("\n[simdgen] Verifying AVX2 batch kernels...")
        batch_rc = verify_avx2_batch()
        if batch_rc != 0:
            verify_failures += 1
        return 0 if verify_failures == 0 else 1

    if not dry_run and not verify_mode:
        print(f"\n[simdgen] Generated {len(generators)} files in {OUTPUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
