PROGRAM = test_bench_self_bench

SRCS = $(PROGRAM).lpr \
       $(SRC_DIR)/nextpas.core.bench.base.pas \
       $(SRC_DIR)/nextpas.core.bench.intf.pas \
       $(SRC_DIR)/nextpas.core.bench.stats.pas \
       $(SRC_DIR)/nextpas.core.bench.report.pas \
       $(SRC_DIR)/nextpas.core.bench.pas \
       $(SRC_DIR)/nextpas.core.time.base.pas \
       $(SRC_DIR)/nextpas.core.sync.mutex.pas

include ../bench_test_common.mk
