PROGRAM = test_bench_stats

SRCS = $(PROGRAM).lpr \
       $(SRC_DIR)/nextpas.core.bench.base.pas \
       $(SRC_DIR)/nextpas.core.bench.intf.pas \
       $(SRC_DIR)/nextpas.core.bench.stats.pas \
       $(SRC_DIR)/nextpas.core.math.scalar.pas \
       $(SRC_DIR)/nextpas.core.math.impl.scalar.pas \
       $(SRC_DIR)/nextpas.core.text.conv.pas \
       $(SRC_DIR)/nextpas.core.sync.mutex.pas

include ../bench_test_common.mk
