[package]
name = "unicode-bench"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "unicode"
harness = false

[dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
icu_collator = "1.5"
icu_normalizer = "1.5"
icu_properties = "1.5"
icu_segmenter = "1.5"
icu_casemap = "1.5"
icu = "1.5"
