.PHONY: clean test test-projection test-source-contracts

clean:
	@:

test: test-projection test-source-contracts

test-projection:
	bash check_system_projection.sh

test-source-contracts:
	bash check_system_source_contracts.sh
