PROGRAM = test_bench_phase_c

SRCS = $(PROGRAM).lpr \
       $(SRC_DIR)/nextpas.core.bench.base.pas \
       $(SRC_DIR)/nextpas.core.bench.intf.pas \
       $(SRC_DIR)/nextpas.core.bench.stats.pas \
       $(SRC_DIR)/nextpas.core.bench.stats.advanced.pas \
       $(SRC_DIR)/nextpas.core.sync.mutex.pas

include ../bench_test_common.mk
