type
  TVecF32x4 = nextpas.core.simd.base.TVecF32x4;
  TVecF32x8 = nextpas.core.simd.base.TVecF32x8;
  TVecF64x2 = nextpas.core.simd.base.TVecF64x2;
  TVecF64x4 = nextpas.core.simd.base.TVecF64x4;
  TVecI32x4 = nextpas.core.simd.base.TVecI32x4;
  TVecI32x8 = nextpas.core.simd.base.TVecI32x8;
  TVecI64x2 = nextpas.core.simd.base.TVecI64x2;
  TVecI16x8 = nextpas.core.simd.base.TVecI16x8;
  TVecI8x16 = nextpas.core.simd.base.TVecI8x16;
  TVecU32x4 = nextpas.core.simd.base.TVecU32x4;
  TVecU64x2 = nextpas.core.simd.base.TVecU64x2;
  TVecU16x8 = nextpas.core.simd.base.TVecU16x8;
  TVecU8x16 = nextpas.core.simd.base.TVecU8x16;
  TVecU32x8 = nextpas.core.simd.base.TVecU32x8;
  TVecU64x4 = nextpas.core.simd.base.TVecU64x4;
  TVecI64x4 = nextpas.core.simd.base.TVecI64x4;
  TVecF32x16 = nextpas.core.simd.base.TVecF32x16;
  TVecF64x8 = nextpas.core.simd.base.TVecF64x8;
  TVecI32x16 = nextpas.core.simd.base.TVecI32x16;
  TVecU32x16 = nextpas.core.simd.base.TVecU32x16;
  TVecU64x8 = nextpas.core.simd.base.TVecU64x8;
  TVecI16x32 = nextpas.core.simd.base.TVecI16x32;
  TVecI8x64 = nextpas.core.simd.base.TVecI8x64;
  TVecU8x64 = nextpas.core.simd.base.TVecU8x64;

  TMask2 = nextpas.core.simd.base.TMask2;
  TMask4 = nextpas.core.simd.base.TMask4;
  TMask8 = nextpas.core.simd.base.TMask8;
  TMask16 = nextpas.core.simd.base.TMask16;
  TMask32 = nextpas.core.simd.base.TMask32;
  TMask64 = nextpas.core.simd.base.TMask64;

  TSimdBackend = nextpas.core.simd.base.TSimdBackend;
  TSimdBackendInfo = nextpas.core.simd.base.TSimdBackendInfo;
  TCPUInfo = nextpas.core.simd.cpuinfo.base.TCPUInfo;
  TSimdBackendArray = nextpas.core.simd.cpuinfo.TSimdBackendArray;

  f32x4 = TVecF32x4;
  f64x2 = TVecF64x2;

  i8x16  = TVecI8x16;
  i16x8  = TVecI16x8;
  i32x4  = TVecI32x4;
  i64x2  = TVecI64x2;

  u8x16  = TVecU8x16;
  u16x8  = TVecU16x8;
  u32x4  = TVecU32x4;
  u64x2  = TVecU64x2;

  f32x8  = TVecF32x8;
  f64x4  = TVecF64x4;
  i32x8  = TVecI32x8;
  i64x4  = TVecI64x4;
  u32x8  = TVecU32x8;
  u64x4  = TVecU64x4;

  f32x16 = TVecF32x16;
  f64x8  = TVecF64x8;
  i32x16 = TVecI32x16;
  u32x16 = TVecU32x16;
  u64x8  = TVecU64x8;
  i16x32 = TVecI16x32;
  i8x64  = TVecI8x64;
  u8x64  = TVecU8x64;
