#!/usr/bin/env python3
"""
Generate nextpas.core.text.unicode.joining_type.inc from extracted/DerivedJoiningType.txt.

Usage:
  python3 core/scripts/gen_unicode_joining_type.py --version 16.0.0 --output-dir core/src
  python3 core/scripts/gen_unicode_joining_type.py --src /path/DerivedJoiningType.txt --output-dir core/src

Ordinals MUST match TJoiningType in types.pas.
Only non-U (Non_Joining) ranges are emitted; lookup default = U.
"""
from __future__ import annotations

import argparse
import os
import sys
import urllib.request
from typing import List, Tuple

DEFAULT_VERSION = "16.0.0"
UCD_URL = "https://www.unicode.org/Public/{version}/ucd/extracted/DerivedJoiningType.txt"

# Ordinals MUST match TJoiningType in types.pas
JT_VALUES = {
    "U": 0,  # Non_Joining (default, not emitted)
    "C": 1,  # Join_Causing
    "D": 2,  # Dual_Joining
    "L": 3,  # Left_Joining
    "R": 4,  # Right_Joining
    "T": 5,  # Transparent
}


def load_text(args: argparse.Namespace) -> str:
    if args.src:
        with open(args.src, encoding="utf-8") as f:
            return f.read()
    url = UCD_URL.format(version=args.version)
    sys.stderr.write(f"fetching {url}\n")
    with urllib.request.urlopen(url) as resp:
        return resp.read().decode("utf-8")


def parse_ranges(text: str) -> List[Tuple[int, int, int]]:
    ranges: List[Tuple[int, int, int]] = []
    for line in text.splitlines():
        body = line.split("#")[0].strip()
        if not body:
            continue
        parts = [p.strip() for p in body.split(";")]
        if len(parts) < 2:
            continue
        cp_range, value = parts[0], parts[1]
        if value not in JT_VALUES:
            raise SystemExit(f"unknown Joining_Type {value!r} in {line!r}")
        if JT_VALUES[value] == 0:
            continue
        if ".." in cp_range:
            lo_s, hi_s = cp_range.split("..")
            lo, hi = int(lo_s, 16), int(hi_s, 16)
        else:
            lo = hi = int(cp_range, 16)
        ranges.append((lo, hi, JT_VALUES[value]))
    ranges.sort()
    merged: List[Tuple[int, int, int]] = []
    for lo, hi, val in ranges:
        if merged and merged[-1][2] == val and merged[-1][1] + 1 == lo:
            merged[-1] = (merged[-1][0], hi, val)
        else:
            merged.append((lo, hi, val))
    return merged


def emit(ranges: List[Tuple[int, int, int]], version: str) -> str:
    lines: List[str] = []
    lines.append(f"// {{Auto-generated by gen_unicode_joining_type.py — Unicode {version}}}")
    lines.append("// Joining_Type from extracted/DerivedJoiningType.txt.")
    lines.append("// Default (unlisted) = U / Non_Joining (ordinal 0).")
    lines.append("//")
    lines.append("// JT values (TJoiningType ordinal):")
    lines.append("//   0=U(Non_Joining), 1=C(Join_Causing), 2=D(Dual_Joining), 3=L(Left_Joining), 4=R(Right_Joining), 5=T(Transparent)")
    lines.append("")
    lines.append("const")
    lines.append(f"  JOINING_TYPE_RANGES_COUNT = {len(ranges)};")
    lines.append("")
    lines.append("  JOINING_TYPE_RANGES: array[0..JOINING_TYPE_RANGES_COUNT - 1] of TCodepointRange3 = (")
    rows = [
        f"    (Lo: ${lo:04X}; Hi: ${hi:04X}; Value: {val})"
        for lo, hi, val in ranges
    ]
    lines.append(",\n".join(rows))
    lines.append("  );")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", default=DEFAULT_VERSION)
    parser.add_argument("--src", default=None)
    parser.add_argument("--output-dir", default="core/src")
    args = parser.parse_args()

    ranges = parse_ranges(load_text(args))
    out = os.path.join(args.output_dir, "nextpas.core.text.unicode.joining_type.inc")
    with open(out, "w", encoding="utf-8") as f:
        f.write(emit(ranges, args.version))
    sys.stderr.write(f"wrote {out} ({len(ranges)} ranges)\n")


if __name__ == "__main__":
    main()
