#!/usr/bin/env python3
"""Generate nextpas.core.text.unicode.special_casing.inc from SpecialCasing.txt.

Only unconditional rows (empty condition list). Final_Sigma is handled in code.

Usage:
  python3 core/scripts/gen_unicode_special_casing.py --version 16.0.0 --output-dir core/src
"""

from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path
from typing import List, Tuple

DEFAULT_VERSION = "16.0.0"
UCD_BASE = "https://www.unicode.org/Public/{version}/ucd/"
MAX_MAP = 8


def download(version: str) -> str:
    url = UCD_BASE.format(version=version) + "SpecialCasing.txt"
    with urllib.request.urlopen(url, timeout=120) as resp:
        return resp.read().decode("utf-8", errors="replace")


def parse_hex_list(s: str) -> List[int]:
    s = s.strip()
    if not s:
        return []
    return [int(x, 16) for x in s.split()]


def parse_special_casing(text: str) -> List[Tuple[int, List[int], List[int], List[int]]]:
    """Return list of (cp, lower, title, upper) for unconditional rows."""
    rows: List[Tuple[int, List[int], List[int], List[int]]] = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        if len(parts) < 4:
            continue
        # code; lower; title; upper; conditions;
        cp = int(parts[0], 16)
        lower = parse_hex_list(parts[1])
        title = parse_hex_list(parts[2])
        upper = parse_hex_list(parts[3])
        cond = parts[4].strip() if len(parts) > 4 else ""
        if cond:
            # skip conditional (Final_Sigma, tr, az, lt, ...)
            continue
        if not lower and not title and not upper:
            continue
        for seq in (lower, title, upper):
            if len(seq) > MAX_MAP:
                raise ValueError(f"map too long for U+{cp:04X}: {seq}")
        rows.append((cp, lower, title, upper))
    rows.sort(key=lambda r: r[0])
    return rows


def pad_map(seq: List[int]) -> str:
    vals = list(seq) + [0] * (MAX_MAP - len(seq))
    return "(" + ", ".join(f"${v:04X}" for v in vals) + ")"


def emit(rows: List[Tuple[int, List[int], List[int], List[int]]], version: str) -> str:
    n = max(len(rows), 1)
    lines = [
        f"// {{Auto-generated by gen_unicode_special_casing.py — UCD {version}}}",
        f"// Unconditional SpecialCasing.txt rows only (no locale / Final_Sigma).",
        f"// Map arrays length-padded to {MAX_MAP}; Len* fields are actual counts.",
        f"// TSpecialCasingEntry is declared in casefold.pas before include.",
        "",
        "const",
        f"  SPECIAL_CASING_COUNT = {len(rows)};",
    ]
    if not rows:
        lines.append(
            "  SPECIAL_CASING: array[0..0] of TSpecialCasingEntry = ("
            "(Cp: 0; LowerLen: 0; TitleLen: 0; UpperLen: 0; "
            "Lower: (0,0,0,0,0,0,0,0); Title: (0,0,0,0,0,0,0,0); Upper: (0,0,0,0,0,0,0,0)));"
        )
        return "\n".join(lines) + "\n"

    lines.append(f"  SPECIAL_CASING: array[0..{len(rows)-1}] of TSpecialCasingEntry = (")
    for i, (cp, lo, ti, up) in enumerate(rows):
        comma = "," if i < len(rows) - 1 else ""
        lines.append(
            f"    (Cp: ${cp:04X}; LowerLen: {len(lo)}; TitleLen: {len(ti)}; UpperLen: {len(up)}; "
            f"Lower: {pad_map(lo)}; Title: {pad_map(ti)}; Upper: {pad_map(up)}){comma}"
        )
    lines.append("  );")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default=DEFAULT_VERSION)
    ap.add_argument("--output-dir", default="core/src")
    ap.add_argument("--src", default="")
    args = ap.parse_args()

    if args.src:
        text = Path(args.src).read_text(encoding="utf-8", errors="replace")
    else:
        print(f"Downloading SpecialCasing.txt {args.version} ...", file=sys.stderr)
        text = download(args.version)

    rows = parse_special_casing(text)
    print(f"unconditional rows={len(rows)}", file=sys.stderr)
    out = emit(rows, args.version)
    path = Path(args.output_dir) / "nextpas.core.text.unicode.special_casing.inc"
    path.write_text(out, encoding="utf-8")
    print(f"Wrote {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
