#!/usr/bin/env python3
"""
Vendor Unicode official conformance fixtures for offline tests.

Downloads (once) and writes compact data files under the test tree.
Does NOT rewrite production .inc lookup tables.

Usage:
    python3 core/scripts/gen_unicode_fixtures.py \\
        --version 16.0.0 \\
        --fixtures-dir core/tests/nextpas.core.text.unicode/data
"""

from __future__ import annotations

import argparse
import os
import sys
import urllib.error
import urllib.request

DEFAULT_VERSION = "16.0.0"
UCD_BASE = "https://www.unicode.org/Public/{version}/ucd/"


def download_ucd(version: str, filename: str) -> str:
    """Download a UCD file; prefer curl (more reliable TLS) then urllib."""
    url = UCD_BASE.format(version=version) + filename
    print(f"  Downloading {url} ...", file=sys.stderr)

    # curl is more reliable on some TLS stacks than urllib.
    try:
        import subprocess

        result = subprocess.run(
            ["curl", "-fsSL", "--retry", "3", "--retry-delay", "1", url],
            check=False,
            capture_output=True,
        )
        if result.returncode == 0 and result.stdout:
            return result.stdout.decode("utf-8", errors="replace")
        print(f"  curl failed (rc={result.returncode}), falling back to urllib", file=sys.stderr)
    except FileNotFoundError:
        pass

    try:
        with urllib.request.urlopen(url, timeout=120) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        print(f"  ERROR: HTTP {e.code} fetching {url}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:  # noqa: BLE001 — surface download failures cleanly
        print(f"  ERROR: {e}", file=sys.stderr)
        sys.exit(1)


def read_text_file(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def write_normalization_fixture(text: str, out_path: str, version: str) -> int:
    """Write data rows only: c1;c2;c3;c4;c5; (strip trailing comments)."""
    rows: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("@"):
            continue
        # drop inline comment
        if "#" in line:
            line = line.split("#", 1)[0].rstrip()
        parts = [p.strip() for p in line.split(";")]
        # official lines end with empty field after c5 → 6 parts; keep first 5
        if len(parts) < 5:
            continue
        c1, c2, c3, c4, c5 = parts[0], parts[1], parts[2], parts[3], parts[4]
        rows.append(f"{c1};{c2};{c3};{c4};{c5}")

    header = (
        f"# Auto-generated by core/scripts/gen_unicode_fixtures.py\n"
        f"# Source: Unicode {version} NormalizationTest.txt\n"
        f"# Format: c1;c2;c3;c4;c5  (hex codepoint sequences, space-separated)\n"
        f"# Rows: {len(rows)}\n"
    )
    body = "\n".join(rows) + ("\n" if rows else "")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(body)
    return len(rows)


def write_break_fixture(text: str, out_path: str, version: str, source_name: str) -> int:
    """
    Write compact UAX#29 break tests (Grapheme or Word).

    Format per line:
      <hex cps space-separated>|<break flags 0/1 before each cp and after last>
    """
    rows: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "#" in line:
            line = line.split("#", 1)[0].rstrip()
        if "÷" not in line and "×" not in line:
            continue

        tokens = line.split()
        if not tokens:
            continue

        cps: list[str] = []
        breaks: list[str] = []
        expect_marker = True
        for tok in tokens:
            if tok in ("÷", "×"):
                if not expect_marker:
                    breaks = []
                    cps = []
                    break
                breaks.append("1" if tok == "÷" else "0")
                expect_marker = False
            else:
                if expect_marker:
                    breaks = []
                    cps = []
                    break
                cps.append(tok.upper())
                expect_marker = True

        if not cps or not breaks or len(breaks) != len(cps) + 1:
            continue
        if breaks[0] != "1" or breaks[-1] != "1":
            continue
        rows.append(f"{' '.join(cps)}|{' '.join(breaks)}")

    header = (
        f"# Auto-generated by core/scripts/gen_unicode_fixtures.py\n"
        f"# Source: Unicode {version} {source_name}\n"
        f"# Format: <hex cps space-separated>|<break flags 0/1 before each cp and after last>\n"
        f"# Rows: {len(rows)}\n"
    )
    body = "\n".join(rows) + ("\n" if rows else "")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(body)
    return len(rows)


def write_grapheme_fixture(text: str, out_path: str, version: str) -> int:
    return write_break_fixture(
        text, out_path, version, "auxiliary/GraphemeBreakTest.txt"
    )


def write_word_fixture(text: str, out_path: str, version: str) -> int:
    return write_break_fixture(
        text, out_path, version, "auxiliary/WordBreakTest.txt"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Vendor Unicode conformance fixtures")
    parser.add_argument("--version", default=DEFAULT_VERSION)
    parser.add_argument(
        "--fixtures-dir",
        default="core/tests/nextpas.core.text.unicode/data",
        help="Directory to write fixture files",
    )
    parser.add_argument(
        "--normalization-src",
        default=None,
        help="Local NormalizationTest.txt (skip download)",
    )
    parser.add_argument(
        "--grapheme-src",
        default=None,
        help="Local GraphemeBreakTest.txt (skip download)",
    )
    parser.add_argument(
        "--word-src",
        default=None,
        help="Local WordBreakTest.txt (skip download)",
    )
    parser.add_argument(
        "--word-only",
        action="store_true",
        help="Only generate word_break_test.txt",
    )
    args = parser.parse_args()

    os.makedirs(args.fixtures_dir, exist_ok=True)
    print(f"Generating Unicode {args.version} conformance fixtures → {args.fixtures_dir}", file=sys.stderr)

    if not args.word_only:
        if args.normalization_src:
            norm_text = read_text_file(args.normalization_src)
        else:
            norm_text = download_ucd(args.version, "NormalizationTest.txt")
        if args.grapheme_src:
            gcb_text = read_text_file(args.grapheme_src)
        else:
            gcb_text = download_ucd(args.version, "auxiliary/GraphemeBreakTest.txt")

        norm_path = os.path.join(args.fixtures_dir, "normalization_test.txt")
        gcb_path = os.path.join(args.fixtures_dir, "grapheme_break_test.txt")
        n_norm = write_normalization_fixture(norm_text, norm_path, args.version)
        n_gcb = write_grapheme_fixture(gcb_text, gcb_path, args.version)
        print(f"  Wrote {norm_path} ({n_norm} rows)", file=sys.stderr)
        print(f"  Wrote {gcb_path} ({n_gcb} rows)", file=sys.stderr)

    if args.word_src:
        word_text = read_text_file(args.word_src)
    else:
        word_text = download_ucd(args.version, "auxiliary/WordBreakTest.txt")
    word_path = os.path.join(args.fixtures_dir, "word_break_test.txt")
    n_word = write_word_fixture(word_text, word_path, args.version)
    print(f"  Wrote {word_path} ({n_word} rows)", file=sys.stderr)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
