#!/usr/bin/env python3
"""
Generate nextpas.core.text.unicode.brackets.inc from BidiBrackets.txt (Unicode 16.0).

Usage:
  python3 core/scripts/gen_unicode_brackets.py --version 16.0.0 --output-dir core/src
  python3 core/scripts/gen_unicode_brackets.py --src /path/BidiBrackets.txt --output-dir core/src
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import urllib.request
from typing import List, Tuple

DEFAULT_VERSION = "16.0.0"
UCD_BASE = "https://www.unicode.org/Public/{version}/ucd/"


def download_ucd(version: str, filename: str) -> str:
    url = UCD_BASE.format(version=version) + filename
    print(f"  Downloading {url} ...", file=sys.stderr)
    try:
        result = subprocess.run(
            ["curl", "-fsSL", "--retry", "3", "--retry-delay", "1", url],
            check=False,
            capture_output=True,
        )
        if result.returncode == 0 and result.stdout:
            return result.stdout.decode("utf-8", errors="replace")
        print(f"  curl failed (rc={result.returncode}), falling back to urllib", file=sys.stderr)
    except FileNotFoundError:
        pass
    try:
        with urllib.request.urlopen(url, timeout=120) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except Exception as e:  # noqa: BLE001
        print(f"  ERROR: {e}", file=sys.stderr)
        sys.exit(1)


def parse_brackets(text: str) -> List[Tuple[int, int, int]]:
    """Return sorted list of (cp, pair, kind) where kind 1=open 2=close."""
    rows: List[Tuple[int, int, int]] = []
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        if len(parts) < 3:
            continue
        cp = int(parts[0], 16)
        pair = int(parts[1], 16)
        kind_s = parts[2].lower()
        if kind_s.startswith("o"):
            kind = 1
        elif kind_s.startswith("c"):
            kind = 2
        else:
            continue
        rows.append((cp, pair, kind))
    rows.sort(key=lambda r: r[0])
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Bidi brackets tables")
    parser.add_argument("--version", default=DEFAULT_VERSION)
    parser.add_argument("--output-dir", default="core/src")
    parser.add_argument("--src", default=None, help="Local BidiBrackets.txt")
    args = parser.parse_args()

    if args.src:
        with open(args.src, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
    else:
        text = download_ucd(args.version, "BidiBrackets.txt")

    rows = parse_brackets(text)
    n = len(rows)
    lines = [
        f"// {{Auto-generated by gen_unicode_brackets.py — Unicode {args.version}}}",
        "// Bidi_Paired_Bracket + Bidi_Paired_Bracket_Type from BidiBrackets.txt.",
        "// Kind: 0=none (not in table), 1=open, 2=close.",
        "",
        "type",
        "  TBidiBracketEntry = record",
        "    Cp: TUnicodeCodepoint;",
        "    Pair: TUnicodeCodepoint;",
        "    Kind: Byte; { 1=open 2=close }",
        "  end;",
        "",
        "const",
        f"  BIDI_BRACKET_COUNT = {n};",
        f"  BIDI_BRACKETS: array[0..{max(n - 1, 0)}] of TBidiBracketEntry = (",
    ]
    if n == 0:
        lines.append("    (Cp: 0; Pair: 0; Kind: 0)")
    else:
        for i, (cp, pair, kind) in enumerate(rows):
            sep = "," if i < n - 1 else ""
            lines.append(f"    (Cp: ${cp:04X}; Pair: ${pair:04X}; Kind: {kind}){sep}")
    lines.append("  );")
    lines.append("")

    out = "\n".join(lines) + "\n"
    os.makedirs(args.output_dir, exist_ok=True)
    path = os.path.join(args.output_dir, "nextpas.core.text.unicode.brackets.inc")
    with open(path, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"Wrote {path} ({len(out)} bytes, {n} brackets)", file=sys.stderr)


if __name__ == "__main__":
    main()
