#!/usr/bin/env python3
"""Generate normalize_qc.inc: NFC/NFD/NFKD/NFKC_QC not-Yes tables (UCD 16.0)."""
from __future__ import annotations

import argparse
import urllib.request
from pathlib import Path
from typing import List, Tuple

VERSION = "16.0.0"
URL = f"https://www.unicode.org/Public/{VERSION}/ucd/DerivedNormalizationProps.txt"
PROPS = ("NFC_QC", "NFD_QC", "NFKD_QC", "NFKC_QC")


def download() -> str:
    with urllib.request.urlopen(URL, timeout=120) as r:
        return r.read().decode("utf-8", errors="replace")


def parse_not_yes(text: str, prop: str) -> List[Tuple[int, int]]:
    ranges: List[Tuple[int, int]] = []
    for line in text.splitlines():
        line0 = line.split("#", 1)[0].strip()
        if not line0 or f"; {prop};" not in line0:
            continue
        parts = [p.strip() for p in line0.split(";")]
        if len(parts) < 3 or parts[1] != prop:
            continue
        if parts[2] not in ("N", "M"):
            continue
        rng = parts[0]
        if ".." in rng:
            a, b = rng.split("..")
            lo, hi = int(a, 16), int(b, 16)
        else:
            lo = hi = int(rng, 16)
        ranges.append((lo, hi))
    return ranges


def build_bmp(ranges: List[Tuple[int, int]]) -> List[int]:
    bits = [0] * 0x10000
    for lo, hi in ranges:
        for cp in range(lo, min(hi, 0xFFFF) + 1):
            bits[cp] = 1
    return bits


def build_smp(ranges: List[Tuple[int, int]]) -> List[Tuple[int, int]]:
    smp: List[Tuple[int, int]] = []
    for lo, hi in ranges:
        if hi < 0x10000:
            continue
        smp.append((max(lo, 0x10000), hi))
    smp.sort()
    return smp


def emit_prop(name: str, bits: List[int], smp: List[Tuple[int, int]]) -> str:
    lines: List[str] = []
    lines.append(f"  // --- {name}_QC not-Yes (N|M) ---")
    lines.append(f"  {name}_QC_NOT_YES_BMP: array[0..255, 0..255] of Byte = (")
    for hi in range(256):
        row = [str(bits[(hi << 8) | lo]) for lo in range(256)]
        groups = [", ".join(row[i : i + 32]) for i in range(0, 256, 32)]
        inner = ",\n     ".join(groups)
        comma = "," if hi < 255 else ""
        lines.append(f"    ({inner}){comma}")
    lines.append("  );")
    if not smp:
        lines.append(f"  {name}_QC_NOT_YES_SMP_COUNT = 1;")
        lines.append(
            f"  {name}_QC_NOT_YES_SMP: array[0..0] of TCodepointRange3 = ("
            f"(Lo: $10000; Hi: $10000; Value: 0));"
        )
    else:
        lines.append(f"  {name}_QC_NOT_YES_SMP_COUNT = {len(smp)};")
        lines.append(
            f"  {name}_QC_NOT_YES_SMP: array[0..{len(smp) - 1}] of TCodepointRange3 = ("
        )
        for i, (lo, hi) in enumerate(smp):
            comma = "," if i < len(smp) - 1 else ""
            lines.append(f"    (Lo: ${lo:06X}; Hi: ${hi:06X}; Value: 1){comma}")
        lines.append("  );")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output-dir", default="core/src")
    ap.add_argument("--src", default="")
    args = ap.parse_args()
    if args.src:
        text = Path(args.src).read_text(encoding="utf-8", errors="replace")
    else:
        print(f"Downloading {URL} ...")
        text = download()
    chunks = [
        f"// {{Auto-generated by gen_unicode_norm_qc.py — UCD {VERSION}}}",
        "// *_QC not-Yes: 1 = N or M. SMP ranges sorted for binary search.",
        "const",
        "",
    ]
    for prop in PROPS:
        short = prop.replace("_QC", "")
        ranges = parse_not_yes(text, prop)
        bits = build_bmp(ranges)
        smp = build_smp(ranges)
        print(f"{prop}: ranges={len(ranges)} bmp_not_yes={sum(bits)} smp={len(smp)}")
        chunks.append(emit_prop(short, bits, smp))
    out = Path(args.output_dir) / "nextpas.core.text.unicode.normalize_qc.inc"
    out.write_text("\n".join(chunks) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
