#!/usr/bin/env python3
"""Generate nextpas.core.text.unicode.eaw.inc from EastAsianWidth.txt (UCD 16.0).

Ordinals MUST match TEastAsianWidth in types.pas:
  eawNeutral=0, eawAmbiguous=1, eawHalfwidth=2,
  eawFullwidth=3, eawNarrow=4, eawWide=5

Usage:
  python3 core/scripts/gen_unicode_eaw.py --version 16.0.0 --output-dir core/src
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path
from typing import Dict, List, Tuple

DEFAULT_VERSION = "16.0.0"
UCD_BASE = "https://www.unicode.org/Public/{version}/ucd/"

# Match TEastAsianWidth ordinals
EAW_ORD = {
    "N": 0,
    "A": 1,
    "H": 2,
    "F": 3,
    "Na": 4,
    "W": 5,
}

LINE_RE = re.compile(
    r"^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*(N|A|H|F|Na|W)\b"
)


def download(version: str) -> str:
    url = UCD_BASE.format(version=version) + "EastAsianWidth.txt"
    with urllib.request.urlopen(url, timeout=120) as resp:
        return resp.read().decode("utf-8", errors="replace")


def parse_eaw(text: str) -> Dict[int, int]:
    """cp -> ordinal (only explicit assignments)."""
    out: Dict[int, int] = {}
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        m = LINE_RE.match(line)
        if not m:
            continue
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        ordv = EAW_ORD[m.group(3)]
        for cp in range(lo, hi + 1):
            out[cp] = ordv
    return out


def build_bmp(table: Dict[int, int]) -> List[List[int]]:
    bmp = [[0] * 256 for _ in range(256)]  # default N=0
    for cp, v in table.items():
        if cp <= 0xFFFF:
            bmp[cp >> 8][cp & 0xFF] = v
    return bmp


def build_smp_ranges(table: Dict[int, int]) -> List[Tuple[int, int, int]]:
    """Merge consecutive SMP cps with same value (skip pure Neutral)."""
    items = sorted((cp, v) for cp, v in table.items() if cp > 0xFFFF)
    if not items:
        return [(0x10000, 0x10000, 0)]
    ranges: List[Tuple[int, int, int]] = []
    lo, prev_v = items[0]
    hi = lo
    for cp, v in items[1:]:
        if cp == hi + 1 and v == prev_v:
            hi = cp
            continue
        if prev_v != 0:  # skip Neutral-only ranges (default)
            ranges.append((lo, hi, prev_v))
        lo, hi, prev_v = cp, cp, v
    if prev_v != 0:
        ranges.append((lo, hi, prev_v))
    if not ranges:
        ranges = [(0x10000, 0x10000, 0)]
    return ranges


def emit_bmp(bmp: List[List[int]]) -> str:
    lines = ["  EAW_BMP_TABLE: array[0..255, 0..255] of Byte = ("]
    for hi in range(256):
        parts = [str(v) for v in bmp[hi]]
        grouped = []
        for base in range(0, 256, 32):
            grouped.append(", ".join(parts[base : base + 32]))
        inner = ",\n     ".join(grouped)
        comma = "," if hi < 255 else ""
        lines.append(f"    ({inner}){comma}  // hi=${hi:02X}")
    lines.append("  );")
    return "\n".join(lines)


def emit_smp(ranges: List[Tuple[int, int, int]]) -> str:
    lines = [
        f"  EAW_SMP_RANGES_COUNT = {len(ranges)};",
        f"  EAW_SMP_RANGES: array[0..{len(ranges) - 1}] of TCodepointRange3 = (",
    ]
    for i, (lo, hi, v) in enumerate(ranges):
        comma = "," if i < len(ranges) - 1 else ""
        lines.append(f"    (Lo: ${lo:06X}; Hi: ${hi:06X}; Value: {v}){comma}")
    lines.append("  );")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default=DEFAULT_VERSION)
    ap.add_argument("--output-dir", default="core/src")
    ap.add_argument("--src", default="", help="Local EastAsianWidth.txt")
    args = ap.parse_args()

    if args.src:
        text = Path(args.src).read_text(encoding="utf-8", errors="replace")
    else:
        print(f"Downloading UCD {args.version} EastAsianWidth.txt ...", file=sys.stderr)
        text = download(args.version)

    table = parse_eaw(text)
    bmp = build_bmp(table)
    smp = build_smp_ranges(table)
    # stats
    from collections import Counter

    c = Counter(table.values())
    print(
        f"entries={len(table)} counts N={c[0]} A={c[1]} H={c[2]} F={c[3]} Na={c[4]} W={c[5]} smp_ranges={len(smp)}",
        file=sys.stderr,
    )

    out = f"""// {{Auto-generated by gen_unicode_eaw.py — UCD {args.version}}}
// East_Asian_Width from EastAsianWidth.txt
// Ordinals: N=0 A=1 H=2 F=3 Na=4 W=5  (TEastAsianWidth)
// Unlisted / default: Neutral (0)

const
{emit_bmp(bmp)}

{emit_smp(smp)}
"""
    path = Path(args.output_dir) / "nextpas.core.text.unicode.eaw.inc"
    path.write_text(out, encoding="utf-8")
    print(f"Wrote {path} ({path.stat().st_size} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
