#!/usr/bin/env python3
"""Generate nextpas.core.text.unicode.idna_mapping.inc from UTS#46 IdnaMappingTable.txt."""
from __future__ import annotations

import argparse
import urllib.request
from pathlib import Path

IDNA_BASE = "https://www.unicode.org/Public/idna/{version}/IdnaMappingTable.txt"

# Pascal TIDNAMapStatus ordinals
STATUS = {
    "valid": 0,
    "mapped": 1,
    "ignored": 2,
    "deviation": 3,
    "disallowed": 4,
    "disallowed_STD3_valid": 5,
    "disallowed_STD3_mapped": 6,
}


def parse_table(text: str):
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        body = line.split("#")[0].strip()
        parts = [p.strip() for p in body.split(";")]
        if len(parts) < 2:
            continue
        cp_range = parts[0]
        status = parts[1]
        if status not in STATUS:
            raise SystemExit(f"unknown status {status!r} in {line}")
        mapping: list[int] = []
        if len(parts) >= 3 and parts[2]:
            mapping = [int(x, 16) for x in parts[2].split()]
        if ".." in cp_range:
            a, b = cp_range.split("..")
            lo, hi = int(a, 16), int(b, 16)
        else:
            lo = hi = int(cp_range, 16)
        rows.append((lo, hi, status, mapping))
    rows.sort(key=lambda r: r[0])
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="16.0.0")
    ap.add_argument("--output-dir", default="core/src")
    ap.add_argument("--input", default="", help="local IdnaMappingTable.txt (skip download)")
    args = ap.parse_args()

    if args.input:
        text = Path(args.input).read_text(encoding="utf-8")
    else:
        url = IDNA_BASE.format(version=args.version)
        print(f"Downloading {url} ...", flush=True)
        text = urllib.request.urlopen(url, timeout=120).read().decode("utf-8")

    rows = parse_table(text)
    pool: list[int] = []
    key_to_off: dict[tuple[int, ...], int] = {}
    out_rows = []
    for lo, hi, status, mapping in rows:
        key = tuple(mapping)
        if key not in key_to_off:
            key_to_off[key] = len(pool)
            pool.extend(mapping)
        out_rows.append((lo, hi, STATUS[status], key_to_off[key], len(mapping)))

    lines = [
        f"// {{Auto-generated by gen_unicode_idna_mapping.py — UTS#46 / idna {args.version}}}",
        "// Source: IdnaMappingTable.txt — do not edit manually.",
        "",
        "const",
        f"  IDNA_MAP_POOL_COUNT = {max(1, len(pool))};",
        f"  IDNA_MAP_RANGES_COUNT = {len(out_rows)};",
        "",
        "  { Mapping codepoint pool (shared by mapped/deviation/STD3_mapped rows). }",
        f"  IDNA_MAP_POOL: array[0..IDNA_MAP_POOL_COUNT - 1] of TUnicodeCodepoint = (",
    ]
    if not pool:
        lines.append("    0")
    else:
        for i, cp in enumerate(pool):
            comma = "," if i < len(pool) - 1 else ""
            lines.append(f"    ${cp:04X}{comma}")
    lines += [
        "  );",
        "",
        "  IDNA_MAP_RANGES: array[0..IDNA_MAP_RANGES_COUNT - 1] of record",
        "    Lo: TUnicodeCodepoint;",
        "    Hi: TUnicodeCodepoint;",
        "    Status: Byte;",
        "    MapOff: UInt32;",
        "    MapLen: Byte;",
        "  end = (",
    ]
    for i, (lo, hi, st, off, ln) in enumerate(out_rows):
        comma = "," if i < len(out_rows) - 1 else ""
        lines.append(
            f"    (Lo: ${lo:04X}; Hi: ${hi:04X}; Status: {st}; MapOff: {off}; MapLen: {ln}){comma}"
        )
    lines.append("  );")
    lines.append("")

    out = Path(args.output_dir) / "nextpas.core.text.unicode.idna_mapping.inc"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"Wrote {out} ranges={len(out_rows)} pool={len(pool)} bytes≈{out.stat().st_size}"
    )


if __name__ == "__main__":
    main()
