#!/usr/bin/env python3
"""
Generate nextpas.core.text.unicode.confusables.inc from UTS#39 confusables.txt.

Usage:
  python3 core/scripts/gen_unicode_confusables.py --version 16.0.0 --output-dir core/src
  python3 core/scripts/gen_unicode_confusables.py --src /path/confusables.txt --output-dir core/src

Single-codepoint sources mapped to prototype sequences (MA table).
The official table is verified to be closed under the mapping (idempotent):
no prototype codepoint may itself have a mapping — hard error otherwise.
NFD is NOT applied here (runtime skeleton uses the in-repo 16.0 NFD).
"""
from __future__ import annotations

import argparse
import os
import sys
import urllib.request
from typing import Dict, Tuple

DEFAULT_VERSION = "16.0.0"
SECURITY_URL = "https://www.unicode.org/Public/security/{version}/confusables.txt"


def load_text(args: argparse.Namespace) -> str:
    if args.src:
        with open(args.src, encoding="utf-8-sig") as f:
            return f.read()
    url = SECURITY_URL.format(version=args.version)
    sys.stderr.write(f"fetching {url}\n")
    with urllib.request.urlopen(url) as resp:
        return resp.read().decode("utf-8-sig")


def parse_map(text: str) -> Dict[int, Tuple[int, ...]]:
    mapping: Dict[int, Tuple[int, ...]] = {}
    for line in text.splitlines():
        body = line.split("#")[0].strip()
        if not body:
            continue
        parts = [p.strip() for p in body.split(";")]
        if len(parts) < 3:
            continue
        if parts[2] != "MA":
            raise SystemExit(f"unexpected type {parts[2]!r} in {line!r}")
        if " " in parts[0]:
            raise SystemExit(f"multi-codepoint source unsupported: {line!r}")
        src = int(parts[0], 16)
        proto = tuple(int(x, 16) for x in parts[1].split())
        if src in mapping and mapping[src] != proto:
            raise SystemExit(f"conflicting mapping for U+{src:04X}")
        mapping[src] = proto
    # Closure check: prototypes must be fixed points of the mapping.
    for src, proto in mapping.items():
        for cp in proto:
            if cp in mapping:
                raise SystemExit(
                    f"table not closed: U+{src:04X} -> U+{cp:04X} which maps further")
    return mapping


def emit(mapping: Dict[int, Tuple[int, ...]], version: str) -> str:
    entries = sorted(mapping.items())
    pool: list[int] = []
    rows: list[str] = []
    for cp, proto in entries:
        offset = len(pool)
        pool.extend(proto)
        rows.append(
            f"    (Cp: ${cp:04X}; Offset: {offset}; Len: {len(proto)})")
    lines: list[str] = []
    lines.append(f"// {{Auto-generated by gen_unicode_confusables.py — UTS#39 {version}}}")
    lines.append("// Source: confusables.txt (MA) — do not edit manually.")
    lines.append("// Sorted by Cp for binary search; prototypes are mapping fixed points.")
    lines.append("")
    lines.append("const")
    lines.append(f"  CONFUSABLE_POOL_COUNT = {len(pool)};")
    lines.append(f"  CONFUSABLE_ENTRIES_COUNT = {len(entries)};")
    lines.append("")
    lines.append("  { Prototype codepoint pool (concatenated sequences). }")
    lines.append("  CONFUSABLE_POOL: array[0..CONFUSABLE_POOL_COUNT - 1] of TUnicodeCodepoint = (")
    lines.append(",\n".join(f"    ${cp:04X}" for cp in pool))
    lines.append("  );")
    lines.append("")
    lines.append("  CONFUSABLE_ENTRIES: array[0..CONFUSABLE_ENTRIES_COUNT - 1] of record")
    lines.append("    Cp: TUnicodeCodepoint;")
    lines.append("    Offset: UInt32;")
    lines.append("    Len: Byte;")
    lines.append("  end = (")
    lines.append(",\n".join(rows))
    lines.append("  );")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", default=DEFAULT_VERSION)
    parser.add_argument("--src", default=None)
    parser.add_argument("--output-dir", default="core/src")
    args = parser.parse_args()

    mapping = parse_map(load_text(args))
    out = os.path.join(args.output_dir, "nextpas.core.text.unicode.confusables.inc")
    with open(out, "w", encoding="utf-8") as f:
        f.write(emit(mapping, args.version))
    sys.stderr.write(f"wrote {out} ({len(mapping)} entries)\n")


if __name__ == "__main__":
    main()
